# Generated by Django 5.2.6 on 2025-11-06 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0002_asistenciadocente_alertas_docentemarcacionlog"),
        ("core", "0036_alter_ventanahabilitacion_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarioAsistenciaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("feriado", "Feriado"),
                            ("suspension", "Suspensión de actividades"),
                            ("licencia", "Licencia institucional"),
                        ],
                        default="feriado",
                        max_length=20,
                    ),
                ),
                (
                    "subtipo",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("licencia_invierno", "Licencia de invierno"),
                            ("licencia_anual", "Licencia anual reglamentaria"),
                            ("otro", "Otro"),
                        ],
                        default="general",
                        max_length=32,
                    ),
                ),
                ("fecha_desde", models.DateField()),
                ("fecha_hasta", models.DateField()),
                ("aplica_docentes", models.BooleanField(default=True)),
                ("aplica_estudiantes", models.BooleanField(default=True)),
                ("motivo", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Evento de calendario de asistencia",
                "verbose_name_plural": "Eventos de calendario de asistencia",
                "ordering": ["-fecha_desde", "-fecha_hasta"],
            },
        ),
        migrations.RenameIndex(
            model_name="asistenciaalumno",
            new_name="asistencia__clase_i_62f809_idx",
            old_name="asistencia__clase__47a97c_idx",
        ),
        migrations.RenameIndex(
            model_name="asistenciaalumno",
            new_name="asistencia__estudia_5c1f5f_idx",
            old_name="asistencia__estudi_7d3f7f_idx",
        ),
        migrations.RenameIndex(
            model_name="asistenciadocente",
            new_name="asistencia__clase_i_2c1de1_idx",
            old_name="asistencia__clase__f207ca_idx",
        ),
        migrations.RenameIndex(
            model_name="asistenciadocente",
            new_name="asistencia__docente_96b222_idx",
            old_name="asistencia__docent_6e90c3_idx",
        ),
        migrations.RenameIndex(
            model_name="asistenciadocente",
            new_name="asistencia__docente_ef3db1_idx",
            old_name="asistencia__docent_1279d7_idx",
        ),
        migrations.RenameIndex(
            model_name="claseprogramada",
            new_name="asistencia__fecha_1fe019_idx",
            old_name="asistencia__fecha_3b6ecf_idx",
        ),
        migrations.RenameIndex(
            model_name="claseprogramada",
            new_name="asistencia__comisio_bb9b4e_idx",
            old_name="asistencia__comisio_3f4b96_idx",
        ),
        migrations.RenameIndex(
            model_name="docentemarcacionlog",
            new_name="asistencia__dni_b81641_idx",
            old_name="asistencia__dni_regi_7522bb_idx",
        ),
        migrations.RenameIndex(
            model_name="docentemarcacionlog",
            new_name="asistencia__resulta_b640a0_idx",
            old_name="asistencia__result_82a876_idx",
        ),
        migrations.AlterField(
            model_name="justificaciondetalle",
            name="aplica_automaticamente",
            field=models.BooleanField(
                default=True,
                help_text="Si está activo, al aprobar la justificación se marcará automáticamente la ausencia como justificada.",
            ),
        ),
        migrations.AddField(
            model_name="calendarioasistenciaevento",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_asistencia_actualizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="calendarioasistenciaevento",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_asistencia_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="calendarioasistenciaevento",
            name="turno",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional. Limita el evento a un turno específico.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_asistencia",
                to="core.turno",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarioasistenciaevento",
            index=models.Index(
                fields=["fecha_desde", "fecha_hasta"],
                name="asistencia__fecha_d_21565f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarioasistenciaevento",
            index=models.Index(fields=["tipo"], name="asistencia__tipo_b2e072_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarioasistenciaevento",
            index=models.Index(fields=["turno"], name="asistencia__turno_i_886d54_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarioasistenciaevento",
            index=models.Index(fields=["activo"], name="asistencia__activo_4a4308_idx"),
        ),
    ]
