# Generated by Django 5.2.6 on 2025-11-08 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0003_calendarioasistenciaevento_and_more"),
        ("core", "0038_correlatividadversion_estudiantecarrera_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarioasistenciaevento",
            name="comision",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional. Limita el evento a una comision/catedra.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_calendario",
                to="core.comision",
            ),
        ),
        migrations.AddField(
            model_name="calendarioasistenciaevento",
            name="docente",
            field=models.ForeignKey(
                blank=True,
                help_text="Asigna un docente cuando se trate de licencias particulares (LAR, invierno, etc.).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_calendario",
                to="core.docente",
            ),
        ),
        migrations.AddField(
            model_name="calendarioasistenciaevento",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional. Limita el evento a un plan de estudio.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_asistencia",
                to="core.plandeestudio",
            ),
        ),
        migrations.AddField(
            model_name="calendarioasistenciaevento",
            name="profesorado",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional. Limita el evento a un profesorado.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_asistencia",
                to="core.profesorado",
            ),
        ),
        migrations.AlterField(
            model_name="calendarioasistenciaevento",
            name="subtipo",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("licencia_invierno", "Licencia especial de invierno"),
                    ("licencia_anual", "Licencia anual reglamentaria (LAR)"),
                    ("licencia_docente", "Licencia docente individual"),
                    ("feria_academica", "Feria / periodo sin asistencia"),
                    ("periodo_sin_asistencia", "Periodo sin toma de asistencia"),
                    ("otro", "Otro"),
                ],
                default="general",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="calendarioasistenciaevento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("feriado", "Feriado"),
                    ("suspension", "Suspensión de actividades"),
                    ("licencia", "Licencia institucional"),
                    ("receso", "Feria/Receso sin asistencia"),
                ],
                default="feriado",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="calendarioasistenciaevento",
            index=models.Index(
                fields=["docente"], name="asistencia__docente_12c64d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarioasistenciaevento",
            index=models.Index(
                fields=["profesorado"], name="asistencia__profeso_d6911d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarioasistenciaevento",
            index=models.Index(fields=["plan"], name="asistencia__plan_id_a59a54_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarioasistenciaevento",
            index=models.Index(
                fields=["comision"], name="asistencia__comisio_8f587b_idx"
            ),
        ),
    ]
