# Generated by Django 5.2.6 on 2025-11-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0005_alter_justificaciondetalle_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistenciaalumno",
            name="estado",
            field=models.CharField(
                choices=[
                    ("presente", "Presente"),
                    ("ausente", "Ausente"),
                    ("ausente_justificada", "Ausente justificada"),
                    ("tarde", "Tarde"),
                ],
                default="ausente",
                max_length=24,
            ),
        ),
    ]
