# Generated by Django 5.2.6 on 2025-11-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0006_alter_asistenciaalumno_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistenciadocente",
            name="marcacion_categoria",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("tarde", "Llegada tarde"),
                    ("diferida", "Carga diferida"),
                ],
                default="normal",
                max_length=12,
            ),
        ),
    ]
