# Generated by Django 5.2.8 on 2026-03-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_cursoestudiantesnapshot_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asistenciaestudiante',
            new_name='asistencia__clase_i_62f809_idx',
            old_name='asistencia__clase_i_9f0a3b_idx',
        ),
        migrations.RenameIndex(
            model_name='asistenciaestudiante',
            new_name='asistencia__estudia_5c1f5f_idx',
            old_name='asistencia__estudia_8cf228_idx',
        ),
        migrations.AlterModelTable(
            name='asistenciaestudiante',
            table='asistencia_asistenciaalumno',
        ),
        migrations.AlterModelTable(
            name='cursoestudiantesnapshot',
            table='asistencia_cursoalumnosnapshot',
        ),
    ]
