# Generated by Django 5.2.8 on 2026-04-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0009_rename_asistencia__clase_i_9f0a3b_idx_asistencia__clase_i_62f809_idx_and_more'),
        ('core', '0080_inscripcionmateriaestudiante_cambio_comision_estado_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='justificaciondetalle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('docente__isnull', True), ('estudiante__isnull', False)), models.Q(('docente__isnull', False), ('estudiante__isnull', True)), _connector='OR'), name='justificacion_estudiante_xor_docente'),
        ),
    ]
