# Generated by Django 5.2.8 on 2026-07-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0010_justificaciondetalle_justificacion_estudiante_xor_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseprogramada',
            name='pin_asistencia',
            field=models.CharField(blank=True, help_text='PIN numérico generado para la asistencia de los estudiantes.', max_length=6, null=True),
        ),
    ]
