# Generated by Django 5.2.8 on 2026-08-11 18:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0011_claseprogramada_pin_asistencia'),
        ('core', '0118_backfill_acta_mesa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cargo', models.CharField(help_text='Código institucional del cargo (ej: CARG-BEDEL-01, CARG-SEC-01).', max_length=64, unique=True)),
                ('codigo_salarial', models.CharField(blank=True, help_text='Código salarial / de liquidación para pagos administrativos.', max_length=64)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del cargo (ej: Bedelía Turno Mañana 01).', max_length=255)),
                ('tipo_cargo', models.CharField(choices=[('horas_reloj', 'Horas Reloj (bloque)'), ('horas_catedra', 'Horas Cátedra')], default='horas_reloj', max_length=32)),
                ('duracion_minutos', models.PositiveIntegerField(default=260, help_text='Duración estándar en minutos por bloque (ej: 260 min = 4hs 20min).')),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'asistencia_cargo',
                'ordering': ['codigo_cargo'],
            },
        ),
        migrations.CreateModel(
            name='CargoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sit_revista', models.CharField(choices=[('titular', 'Titular'), ('interino', 'Interino'), ('suplente', 'Suplente')], default='interino', max_length=16)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('resolucion', models.CharField(blank=True, help_text='Número o detalle de disposición/resolución administrativa.', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_docentes', to='asistencia.cargo')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_asignados', to='core.docente')),
            ],
            options={
                'verbose_name': 'Asignación de cargo a docente',
                'verbose_name_plural': 'Asignaciones de cargo a docentes',
                'db_table': 'asistencia_cargodocente',
                'ordering': ['cargo', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='asistencia.cargo')),
            ],
            options={
                'verbose_name': 'Horario de cargo',
                'verbose_name_plural': 'Horarios de cargo',
                'db_table': 'asistencia_horariocargo',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('cargo', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaCargoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('justificada', 'Ausente justificada'), ('tarde', 'Llegada tarde')], default='presente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_cargos_registradas', to=settings.AUTH_USER_MODEL)),
                ('cargo_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.cargodocente')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to='asistencia.horariocargo')),
            ],
            options={
                'verbose_name': 'Asistencia a cargo docente',
                'verbose_name_plural': 'Asistencias a cargos docentes',
                'db_table': 'asistencia_asistenciacargodocente',
                'ordering': ['-fecha', 'cargo_docente'],
                'unique_together': {('cargo_docente', 'fecha')},
            },
        ),
    ]
