# Generated by Django 5.2.8 on 2026-08-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0012_cargo_cargodocente_horariocargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseprogramada',
            name='pin_expira_en',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de expiración del PIN de asistencia (5 minutos de validez).', null=True),
        ),
    ]
