# Generated by Django 5.2.17 on 2026-09-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0013_claseprogramada_pin_expira_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claseprogramada',
            name='pin_expira_en',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de expiración del PIN de asistencia (20 minutos de validez).', null=True),
        ),
    ]
