# Generated by Django 5.2.8 on 2026-09-04 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0125_riesgoacademicoestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_snapshot', models.DateField(db_index=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('presentes', models.IntegerField(default=0)),
                ('ausentes', models.IntegerField(default=0)),
                ('tardias', models.IntegerField(default=0)),
                ('justificadas', models.IntegerField(default=0)),
                ('porcentaje_asistencia', models.FloatField(blank=True, null=True)),
                ('detalles', models.JSONField(default=dict, help_text='Detalles adicionales por comisión si aplica.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profesorado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencia_snapshots', to='core.profesorado')),
            ],
            options={
                'verbose_name': 'Snapshot de Asistencia',
                'verbose_name_plural': 'Snapshots de Asistencia',
                'ordering': ['-fecha_snapshot'],
                'indexes': [models.Index(fields=['fecha_snapshot'], name='metrics_asi_fecha_s_3883f5_idx'), models.Index(fields=['profesorado', 'fecha_snapshot'], name='metrics_asi_profeso_a6c3f9_idx')],
                'unique_together': {('profesorado', 'fecha_snapshot')},
            },
        ),
        migrations.CreateModel(
            name='AusentismoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_snapshot', models.DateField(db_index=True)),
                ('tasa_ausentismo', models.FloatField(help_text='Porcentaje de ausencias sobre total de asistencias registradas.')),
                ('total_estudiantes', models.IntegerField(default=0)),
                ('estudiantes_sin_registro', models.IntegerField(default=0)),
                ('estudiantes_críticos', models.IntegerField(default=0, help_text='Estudiantes con más del 30% de ausencias.')),
                ('detalles', models.JSONField(default=dict, help_text="Desglose: {'ausencias': N, 'tardias': N, 'total_clases': N, ...}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ausentismo_snapshots', to='core.comision')),
                ('profesorado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ausentismo_snapshots', to='core.profesorado')),
            ],
            options={
                'verbose_name': 'Snapshot de Ausentismo',
                'verbose_name_plural': 'Snapshots de Ausentismo',
                'ordering': ['-fecha_snapshot'],
                'indexes': [models.Index(fields=['fecha_snapshot'], name='metrics_aus_fecha_s_9028b2_idx'), models.Index(fields=['profesorado', 'fecha_snapshot'], name='metrics_aus_profeso_9ba41f_idx')],
                'unique_together': {('comision', 'fecha_snapshot')},
            },
        ),
        migrations.CreateModel(
            name='MatriculaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_snapshot', models.DateField(db_index=True, help_text='Fecha del snapshot (diario, mensual según configuración).')),
                ('total_matriculados', models.IntegerField(default=0)),
                ('por_estado', models.JSONField(default=dict, help_text="Desglose por estado_academico: {'activo': N, 'libre': N, ...}")),
                ('promedio_notas', models.FloatField(blank=True, null=True)),
                ('promedio_asistencia', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profesorado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matricula_snapshots', to='core.profesorado')),
            ],
            options={
                'verbose_name': 'Snapshot de Matrícula',
                'verbose_name_plural': 'Snapshots de Matrícula',
                'ordering': ['-fecha_snapshot'],
                'indexes': [models.Index(fields=['fecha_snapshot'], name='metrics_mat_fecha_s_e32248_idx'), models.Index(fields=['profesorado', 'fecha_snapshot'], name='metrics_mat_profeso_33b574_idx')],
                'unique_together': {('profesorado', 'fecha_snapshot')},
            },
        ),
    ]
