export const drawerWidth = 280;
export const collapsedDrawerWidth = 0;

export const ROLE_NAV_MAP: Record<string, string[]> = {
	admin: [
		"dashboard",
		"analytics",
		"preinscripciones",
		"carreras",
		"reportes",
		"asistencia",
		"cursoIntro",
		"mensajes",
		"secretaria",
		"bedeles",
		"docentes",
		"tutorias",
		"equivalencias",
		"titulos",
		"coordinacion",
		"jefatura",
		"estudiante",
		"primeraCarga",
	],
	secretaria: [
		"dashboard",
		"analytics",
		"preinscripciones",
		"carreras",
		"reportes",
		"asistencia",
		"cursoIntro",
		"mensajes",
		"secretaria",
		"bedeles",
		"docentes",
		"tutorias",
		"equivalencias",
		"titulos",
		"coordinacion",
		"jefatura",
		"estudiante",
		"primeraCarga",
	],
	bedel: [
		"bedeles",
		"mensajes",
		"estudiante",
		"asistencia",
		"cursoIntro",
		"primeraCarga",
		"carreras",
	],
	bedel_secretaria: [
		"bedeles",
		"mensajes",
		"estudiante",
		"asistencia",
		"cursoIntro",
		"carreras",
	],
	docente: ["docentes", "mensajes"],
	tutor: ["tutorias", "analytics", "mensajes", "reportes", "cursoIntro"],
	coordinador: [
		"coordinacion",
		"analytics",
		"mensajes",
		"estudiante",
		"reportes",
		"cursoIntro",
	],
	jefes: ["jefatura", "analytics", "mensajes", "reportes", "estudiante"],
	jefa_aaee: ["jefatura", "analytics", "mensajes", "reportes", "estudiante"],
	consulta: ["dashboard", "analytics", "reportes", "mensajes"],
	estudiante: ["estudiante", "mensajes"],
	equivalencias: ["equivalencias", "mensajes"],
	titulos: ["titulos", "mensajes"],
	curso_intro: ["cursoIntro", "mensajes"],
	attp: ["attp", "estudiante", "mensajes", "primeraCarga"],
	rectorado: ["rectorado", "analytics", "estudiante", "mensajes", "asistencia"],
};

export const roleLabels: Record<string, string> = {
	admin: "Administrador",
	secretaria: "Secretaría",
	bedel: "Bedelía",
	bedel_secretaria: "Bedelía de Secretaría",
	docente: "Docente",
	tutor: "Tutoría",
	coordinador: "Coordinación",
	jefes: "Jefatura",
	jefa_aaee: "Jefa A.A.E.E.",
	consulta: "Consulta",
	estudiante: "Estudiante",
	equivalencias: "Equivalencias",
	titulos: "Títulos",
	curso_intro: "Curso Intro",
	attp: "A.T.T.P.",
	rectorado: "Rectorado",
};

export const roleHomeMap: Record<string, string> = {
	admin: "/dashboard",
	secretaria: "/secretaria",
	bedel: "/bedeles",
	bedel_secretaria: "/bedeles",
	docente: "/docentes",
	tutor: "/tutorias",
	coordinador: "/coordinacion",
	jefes: "/jefatura",
	jefa_aaee: "/jefatura",
	consulta: "/dashboard",
	estudiante: "/estudiantes",
	equivalencias: "/equivalencias",
	titulos: "/titulos",
	curso_intro: "/curso-introductorio",
	attp: "/attp",
	rectorado: "/rectorado",
};

export const navButtonSx = {
	borderRadius: 10,
	mx: 2,
	my: 0.5,
	color: "#ffffff",
	"& .MuiListItemIcon-root": { color: "inherit", minWidth: 32 },
	"& .MuiListItemText-primary": { fontWeight: 600, fontSize: 14 },
	"&.Mui-selected": {
		backgroundColor: "rgba(79, 70, 229,0.35)",
		boxShadow: "0 15px 35px rgba(13, 148, 136,0.45)",
	},
	"&:hover": {
		backgroundColor: "rgba(13, 148, 136,0.25)",
	},
};
