# Generated by Django 5.2.6 on 2025-09-26 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_profesorado_inscripcion_abierta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=120)),
                ("apellido", models.CharField(max_length=120)),
                ("dni", models.CharField(max_length=20, unique=True)),
                ("cuil", models.CharField(max_length=20, unique=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("estado_civil", models.CharField(blank=True, max_length=30)),
                ("nacionalidad", models.CharField(blank=True, max_length=60)),
                ("pais_nacimiento", models.CharField(blank=True, max_length=60)),
                ("provincia_nacimiento", models.CharField(blank=True, max_length=60)),
                ("localidad_nacimiento", models.CharField(blank=True, max_length=120)),
                ("domicilio", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=150)),
                ("tel_movil", models.CharField(blank=True, max_length=50)),
                ("tel_fijo", models.CharField(blank=True, max_length=50)),
                (
                    "contacto_emergencia_tel",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "contacto_emergencia_parentesco",
                    models.CharField(blank=True, max_length=60),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreinscripcionArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preinscripcion_id", models.BigIntegerField(db_index=True)),
                ("tipo", models.CharField(max_length=50)),
                ("archivo", models.FileField(upload_to="preinscripciones/%Y/%m/%d/")),
                ("nombre_original", models.CharField(max_length=255)),
                ("tamano", models.BigIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("subido_por_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "core_preinscripcion_archivo",
            },
        ),
        migrations.CreateModel(
            name="AlumnoEstudioSec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=150)),
                ("establecimiento", models.CharField(blank=True, max_length=150)),
                ("fecha_egreso", models.DateField(blank=True, null=True)),
                ("localidad", models.CharField(blank=True, max_length=120)),
                ("provincia", models.CharField(blank=True, max_length=120)),
                ("pais", models.CharField(blank=True, max_length=60)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudios_sec",
                        to="preinscriptions.alumno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlumnoEstudioSup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=150)),
                ("establecimiento", models.CharField(blank=True, max_length=150)),
                ("fecha_egreso", models.DateField(blank=True, null=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudios_sup",
                        to="preinscriptions.alumno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlumnoLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trabaja_actualmente", models.BooleanField(default=False)),
                ("empleador", models.CharField(blank=True, max_length=150)),
                ("horario_trabajo", models.CharField(blank=True, max_length=100)),
                ("domicilio_laboral", models.CharField(blank=True, max_length=200)),
                (
                    "alumno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laboral",
                        to="preinscriptions.alumno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Preinscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="ENVIADA",
                        max_length=20,
                    ),
                ),
                ("foto_4x4_dataurl", models.TextField(blank=True, null=True)),
                ("foto_4x4_w", models.IntegerField(blank=True, null=True)),
                ("foto_4x4_h", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preinscripciones",
                        to="preinscriptions.alumno",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="preinscripciones",
                        to="core.profesorado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_dni", models.BooleanField(default=False)),
                ("doc_secundario", models.BooleanField(default=False)),
                ("doc_constancia_cuil", models.BooleanField(default=False)),
                ("doc_cert_trabajo", models.BooleanField(default=False)),
                ("doc_buenasalud", models.BooleanField(default=False)),
                ("doc_foto4x4", models.BooleanField(default=False)),
                ("doc_titulo_en_tramite", models.BooleanField(default=False)),
                ("doc_otro", models.BooleanField(default=False)),
                (
                    "preinscripcion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documento_check",
                        to="preinscriptions.preinscripcion",
                    ),
                ),
            ],
        ),
    ]
