# Generated by Django 5.2.6 on 2025-10-01 02:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("preinscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumnolaboral",
            name="alumno",
        ),
        migrations.RemoveField(
            model_name="alumnoestudiosec",
            name="alumno",
        ),
        migrations.RemoveField(
            model_name="alumnoestudiosup",
            name="alumno",
        ),
        migrations.RemoveField(
            model_name="preinscripcion",
            name="alumno",
        ),
        migrations.RemoveField(
            model_name="documentocheck",
            name="preinscripcion",
        ),
        migrations.RemoveField(
            model_name="preinscripcion",
            name="carrera",
        ),
        migrations.DeleteModel(
            name="PreinscripcionArchivo",
        ),
        migrations.DeleteModel(
            name="AlumnoLaboral",
        ),
        migrations.DeleteModel(
            name="AlumnoEstudioSec",
        ),
        migrations.DeleteModel(
            name="AlumnoEstudioSup",
        ),
        migrations.DeleteModel(
            name="Alumno",
        ),
        migrations.DeleteModel(
            name="DocumentoCheck",
        ),
        migrations.DeleteModel(
            name="Preinscripcion",
        ),
    ]
