# Generated by Django 5.2.6 on 2025-10-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("preinscriptions", "0002_remove_alumnolaboral_alumno_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreinscripcionArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preinscripcion_id", models.BigIntegerField(db_index=True)),
                ("tipo", models.CharField(max_length=50)),
                ("archivo", models.FileField(upload_to="preinscripciones/%Y/%m/%d/")),
                ("nombre_original", models.CharField(max_length=255)),
                ("tamano", models.BigIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("subido_por_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "core_preinscripcion_archivo",
            },
        ),
    ]
