# Generated by Django 5.2.6 on 2025-09-25 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                (
                    "cuil",
                    models.CharField(
                        help_text="CUIL sin guiones", max_length=13, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("obligatorio", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlanDeEstudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resolucion",
                    models.CharField(
                        help_text="Número de resolución o normativa del plan",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "anio_inicio",
                    models.IntegerField(
                        help_text="Año en que el plan entró en vigencia"
                    ),
                ),
                (
                    "anio_fin",
                    models.IntegerField(
                        blank=True,
                        help_text="Año en que el plan dejó de estar vigente (opcional)",
                        null=True,
                    ),
                ),
                (
                    "vigente",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si este plan de estudio está actualmente en uso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profesorado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre completo del profesorado o carrera",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "duracion_anios",
                    models.IntegerField(help_text="Duración de la carrera en años"),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el profesorado está actualmente activo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "anio_cursada",
                    models.IntegerField(
                        help_text="Año de la carrera al que pertenece la materia (1, 2, 3, 4, ...)"
                    ),
                ),
                (
                    "carga_horaria_semanal",
                    models.IntegerField(
                        help_text="Cantidad de horas cátedra por semana"
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("ASI", "Asignatura"),
                            ("MOD", "Módulo"),
                            ("TAL", "Taller"),
                            ("LAB", "Laboratorio"),
                            ("SEM", "Seminario"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "tipo_cursada",
                    models.CharField(
                        choices=[
                            ("ANU", "Anual"),
                            ("PCU", "Primer Cuatrimestre"),
                            ("SCU", "Segundo Cuatrimestre"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "docente_titular",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materias_titular",
                        to="core.docente",
                    ),
                ),
                (
                    "plan_de_estudio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias",
                        to="core.plandeestudio",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plandeestudio",
            name="profesorado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planes",
                to="core.profesorado",
            ),
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legajo",
                    models.CharField(
                        help_text="Número de legajo único del estudiante",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("dni", models.CharField(max_length=10, unique=True)),
                ("fecha_nacimiento", models.DateField()),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("domicilio", models.CharField(blank=True, max_length=255)),
                (
                    "estado_legajo",
                    models.CharField(
                        choices=[
                            ("COM", "Completo"),
                            ("INC", "Incompleto / Condicional"),
                            ("PEN", "Pendiente de Revisión"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                (
                    "documentacion_presentada",
                    models.ManyToManyField(
                        blank=True,
                        related_name="estudiantes_que_presentaron",
                        to="core.documento",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudiante",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "carreras",
                    models.ManyToManyField(
                        related_name="estudiantes", to="core.profesorado"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Correlatividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RPC", "Regular para Cursar"),
                            ("APC", "Aprobada para Cursar"),
                            ("APR", "Aprobada para Rendir Final"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "materia_correlativa",
                    models.ForeignKey(
                        help_text="Materia que debe ser aprobada/regularizada (ej: Pedagogía)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="es_correlativa_de",
                        to="core.materia",
                    ),
                ),
                (
                    "materia_origen",
                    models.ForeignKey(
                        help_text="Materia que requiere la correlatividad (ej: Didáctica II)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correlativas_requeridas",
                        to="core.materia",
                    ),
                ),
            ],
            options={
                "unique_together": {("materia_origen", "materia_correlativa", "tipo")},
            },
        ),
    ]
