# Generated by Django 5.2.6 on 2025-09-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesorado",
            name="inscripcion_abierta",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la preinscripción a esta carrera está abierta",
            ),
        ),
    ]
