# Generated by Django 5.2.6 on 2025-09-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_profesorado_inscripcion_abierta"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreAlumno",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("dni", models.CharField(max_length=20, unique=True)),
                ("nombres", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                ("cuil", models.CharField(max_length=20, null=True)),
                ("fecha_nacimiento", models.DateField(null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("telefono", models.CharField(max_length=50, null=True)),
                ("domicilio", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "core_alumno",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CorePreinscripcion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=30)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Enviada", "Enviada"),
                            ("Observada", "Observada"),
                            ("Confirmada", "Confirmada"),
                            ("Rechazada", "Rechazada"),
                            ("Borrador", "Borrador"),
                        ],
                        default="Enviada",
                        max_length=15,
                    ),
                ),
                ("foto_4x4_dataurl", models.TextField(null=True)),
            ],
            options={
                "db_table": "core_preinscripcion",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="profesorado",
            options={"managed": False},
        ),
    ]
