# Generated by Django 5.2.6 on 2025-09-28 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_corealumno_corepreinscripcion_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profesorado",
            table="core_profesorado",
        ),
    ]
