# Generated by Django 5.2.6 on 2025-10-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_profesorado_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materia",
            options={"ordering": ["anio_cursada", "nombre"]},
        ),
        migrations.AlterModelOptions(
            name="profesorado",
            options={},
        ),
        migrations.AlterField(
            model_name="materia",
            name="formato",
            field=models.CharField(
                choices=[
                    ("ASI", "Asignatura"),
                    ("PRA", "Práctica"),
                    ("MOD", "Módulo"),
                    ("TAL", "Taller"),
                    ("LAB", "Laboratorio"),
                    ("SEM", "Seminario"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="materia",
            unique_together={("plan_de_estudio", "anio_cursada", "nombre")},
        ),
    ]
