# Generated by Django 5.2.6 on 2025-10-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_materia_options_alter_profesorado_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materia",
            name="docente_titular",
        ),
        migrations.AddField(
            model_name="docente",
            name="dni",
            field=models.CharField(
                default=0, help_text="DNI del docente", max_length=20, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="docente",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="docente",
            name="telefono",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="docente",
            name="cuil",
            field=models.CharField(
                blank=True,
                help_text="CUIL sin guiones (opcional)",
                max_length=13,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="profesorado",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="profesorado",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="profesorado",
            name="inscripcion_abierta",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="profesorado",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name="profesorado",
            table=None,
        ),
    ]
