# Generated by Django 5.2.6 on 2025-10-01 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_materia_docente_titular_docente_dni_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
            },
        ),
        migrations.RemoveField(
            model_name="materia",
            name="carga_horaria_semanal",
        ),
        migrations.RemoveField(
            model_name="materia",
            name="tipo_cursada",
        ),
        migrations.AddField(
            model_name="materia",
            name="horas_semana",
            field=models.IntegerField(
                default=0, help_text="Carga horaria semanal requerida"
            ),
        ),
        migrations.AddField(
            model_name="materia",
            name="regimen",
            field=models.CharField(
                choices=[
                    ("ANU", "Anual"),
                    ("PCU", "Primer Cuatrimestre"),
                    ("SCU", "Segundo Cuatrimestre"),
                ],
                default="ANU",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="HorarioCatedra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio_cursada", models.IntegerField()),
                (
                    "cuatrimestre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ANU", "Anual"),
                            ("PCU", "Primer Cuatrimestre"),
                            ("SCU", "Segundo Cuatrimestre"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_catedra",
                        to="core.materia",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_catedra",
                        to="core.turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario de Cátedra",
                "verbose_name_plural": "Horarios de Cátedra",
                "unique_together": {
                    ("espacio", "turno", "anio_cursada", "cuatrimestre")
                },
            },
        ),
        migrations.CreateModel(
            name="Bloque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.IntegerField(
                        choices=[
                            (1, "Lunes"),
                            (2, "Martes"),
                            (3, "Miércoles"),
                            (4, "Jueves"),
                            (5, "Viernes"),
                            (6, "Sábado"),
                        ]
                    ),
                ),
                ("hora_desde", models.TimeField()),
                ("hora_hasta", models.TimeField()),
                ("es_recreo", models.BooleanField(default=False)),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloques",
                        to="core.turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloque Horario",
                "verbose_name_plural": "Bloques Horarios",
                "ordering": ["dia", "hora_desde"],
                "unique_together": {("turno", "dia", "hora_desde", "hora_hasta")},
            },
        ),
        migrations.CreateModel(
            name="HorarioCatedraDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bloque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bloque"
                    ),
                ),
                (
                    "horario_catedra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="core.horariocatedra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Horario de Cátedra",
                "verbose_name_plural": "Detalles de Horario de Cátedra",
                "unique_together": {("horario_catedra", "bloque")},
            },
        ),
    ]
