# Generated by Django 5.2.6 on 2025-10-01 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_turno_remove_materia_carga_horaria_semanal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preinscripcion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=30)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Enviada", "Enviada"),
                            ("Observada", "Observada"),
                            ("Confirmada", "Confirmada"),
                            ("Rechazada", "Rechazada"),
                            ("Borrador", "Borrador"),
                        ],
                        default="Enviada",
                        max_length=15,
                    ),
                ),
                ("anio", models.IntegerField()),
                ("foto_4x4_dataurl", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.estudiante",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.profesorado",
                    ),
                ),
            ],
            options={
                "db_table": "preinscripciones",
                "managed": True,
                "unique_together": {("alumno", "carrera", "anio")},
            },
        ),
        migrations.DeleteModel(
            name="CoreAlumno",
        ),
        migrations.DeleteModel(
            name="CorePreinscripcion",
        ),
    ]
