# Generated by Django 5.2.6 on 2025-10-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_preinscripcion_delete_corealumno_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="legajo",
            field=models.CharField(
                blank=True,
                help_text="Número de legajo único del estudiante",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
