# Generated by Django 5.2.6 on 2025-10-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_estudiante_legajo"),
    ]

    operations = [
        migrations.CreateModel(
            name="VentanaHabilitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INSCRIPCION", "Inscripción (general)"),
                            ("MESAS_FINALES", "Mesas de examen - Finales"),
                            ("MESAS_EXTRA", "Mesas de examen - Extraordinarias"),
                            ("MESAS_LIBRES", "Mesas de examen - Libres"),
                            ("MATERIAS", "Inscripciones a Materias"),
                            ("CARRERAS", "Inscripciones a Carreras"),
                            ("COMISION", "Cambios de Comisión"),
                            ("ANALITICOS", "Pedidos de Analíticos"),
                        ],
                        max_length=32,
                    ),
                ),
                ("desde", models.DateField()),
                ("hasta", models.DateField()),
                ("activo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
