# Generated by Django 5.2.6 on 2025-10-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_equivalenciacurricular_mesaexamen_pedidoanalitico_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreinscripcionChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni_legalizado", models.BooleanField(default=False)),
                ("fotos_4x4", models.BooleanField(default=False)),
                ("certificado_salud", models.BooleanField(default=False)),
                ("folios_oficio", models.IntegerField(default=0)),
                ("titulo_secundario_legalizado", models.BooleanField(default=False)),
                ("certificado_titulo_en_tramite", models.BooleanField(default=False)),
                ("analitico_legalizado", models.BooleanField(default=False)),
                ("certificado_alumno_regular_sec", models.BooleanField(default=False)),
                ("adeuda_materias", models.BooleanField(default=False)),
                ("adeuda_materias_detalle", models.TextField(blank=True, default="")),
                (
                    "escuela_secundaria",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("es_certificacion_docente", models.BooleanField(default=False)),
                ("titulo_terciario_univ", models.BooleanField(default=False)),
                (
                    "estado_legajo",
                    models.CharField(
                        choices=[
                            ("COM", "Completo"),
                            ("INC", "Incompleto / Condicional"),
                            ("PEN", "Pendiente de Revisi√≥n"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preinscripcion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="core.preinscripcion",
                    ),
                ),
            ],
        ),
    ]
