# Generated by Django 5.2.6 on 2025-10-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_add_inscripcion_materia_alumno"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="horariocatedra",
            options={
                "verbose_name": "Horario de Cátedra",
                "verbose_name_plural": "Horarios de Cátedra",
            },
        ),
        migrations.AlterModelOptions(
            name="horariocatedradetalle",
            options={
                "verbose_name": "Detalle de Horario de Cátedra",
                "verbose_name_plural": "Detalles de Horario de Cátedra",
            },
        ),
        migrations.RemoveField(
            model_name="preinscripcion",
            name="created_at",
        ),
        migrations.AddField(
            model_name="preinscripcion",
            name="datos_extra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="bloque",
            name="dia",
            field=models.IntegerField(
                choices=[
                    (1, "Lunes"),
                    (2, "Martes"),
                    (3, "Miércoles"),
                    (4, "Jueves"),
                    (5, "Viernes"),
                    (6, "Sábado"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="correlatividad",
            name="materia_correlativa",
            field=models.ForeignKey(
                help_text="Materia que debe ser aprobada/regularizada (ej: Pedagogía)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="es_correlativa_de",
                to="core.materia",
            ),
        ),
        migrations.AlterField(
            model_name="correlatividad",
            name="materia_origen",
            field=models.ForeignKey(
                help_text="Materia que requiere la correlatividad (ej: Didáctica II)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correlativas_requeridas",
                to="core.materia",
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="estado_legajo",
            field=models.CharField(
                choices=[
                    ("COM", "Completo"),
                    ("INC", "Incompleto / Condicional"),
                    ("PEN", "Pendiente de Revisión"),
                ],
                default="PEN",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="legajo",
            field=models.CharField(
                blank=True,
                help_text="Número de legajo único del estudiante",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="materia",
            name="anio_cursada",
            field=models.IntegerField(
                help_text="Año de la carrera al que pertenece la materia (1, 2, 3, 4, ...)"
            ),
        ),
        migrations.AlterField(
            model_name="materia",
            name="formato",
            field=models.CharField(
                choices=[
                    ("ASI", "Asignatura"),
                    ("PRA", "Práctica"),
                    ("MOD", "Módulo"),
                    ("TAL", "Taller"),
                    ("LAB", "Laboratorio"),
                    ("SEM", "Seminario"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="pedidoanalitico",
            name="cohorte",
            field=models.IntegerField(
                blank=True, help_text="Año de ingreso (cohorte)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="plandeestudio",
            name="anio_fin",
            field=models.IntegerField(
                blank=True,
                help_text="Año en que el plan dejó de estar vigente (opcional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plandeestudio",
            name="anio_inicio",
            field=models.IntegerField(help_text="Año en que el plan entró en vigencia"),
        ),
        migrations.AlterField(
            model_name="plandeestudio",
            name="resolucion",
            field=models.CharField(
                help_text="Número de resolución o normativa del plan",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="plandeestudio",
            name="vigente",
            field=models.BooleanField(
                default=True,
                help_text="Indica si este plan de estudio está actualmente en uso",
            ),
        ),
        migrations.AlterField(
            model_name="preinscripcionchecklist",
            name="estado_legajo",
            field=models.CharField(
                choices=[
                    ("COM", "Completo"),
                    ("INC", "Incompleto / Condicional"),
                    ("PEN", "Pendiente de Revisión"),
                ],
                default="PEN",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="profesorado",
            name="duracion_anios",
            field=models.IntegerField(help_text="Duración de la carrera en años"),
        ),
        migrations.AlterField(
            model_name="regularidad",
            name="situacion",
            field=models.CharField(
                choices=[
                    ("PRO", "Promocionado"),
                    ("REG", "Regular"),
                    ("APR", "Aprobado (sin final)"),
                    ("DPA", "Desaprobado por Parciales"),
                    ("DTP", "Desaprobado por Trabajos Prácticos"),
                    ("LBI", "Libre por Inasistencias"),
                    ("LAT", "Libre Antes de Tiempo"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="ventanahabilitacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("INSCRIPCION", "Inscripción (general)"),
                    ("MESAS_FINALES", "Mesas de examen - Finales"),
                    ("MESAS_EXTRA", "Mesas de examen - Extraordinarias"),
                    ("MESAS_LIBRES", "Mesas de examen - Libres"),
                    ("MATERIAS", "Inscripciones a Materias"),
                    ("CARRERAS", "Inscripciones a Carreras"),
                    ("COMISION", "Cambios de Comisión"),
                    ("ANALITICOS", "Pedidos de Analíticos"),
                    ("PREINSCRIPCION", "Preinscripción"),
                ],
                max_length=32,
            ),
        ),
    ]
