# Generated by Django 5.2.6 on 2025-10-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_add_preinscripcion_datos_extra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preinscripcion",
            name="datos_extra",
        ),
        migrations.AddField(
            model_name="preinscripcion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
