# Generated by Django 5.2.6 on 2025-10-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_preinscripcion_datos_extra_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preinscripcion",
            name="datos_extra",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
