# Generated by Django 5.2.6 on 2025-10-17 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_preinscripcion_activa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preinscripcion",
            name="cuil",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{2}-\\d{8}-\\d{1}",
                        message="El CUIL debe tener el formato XX-XXXXXXXX-X.",
                    )
                ],
            ),
        ),
    ]
