# Generated by Django 5.2.6 on 2025-10-18 04:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_preinscripcion_cuil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preinscripcion",
            name="foto_4x4_dataurl",
        ),
    ]
