# Generated by Django 5.2.6 on 2025-10-19 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_remove_preinscripcion_foto_4x4_dataurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripcionmateriaalumno",
            name="estado",
            field=models.CharField(
                choices=[
                    ("CONF", "Confirmada"),
                    ("PEND", "Pendiente"),
                    ("RECH", "Rechazada"),
                    ("ANUL", "Anulada"),
                ],
                default="CONF",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="inscripcionmateriaalumno",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Comision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio_lectivo",
                    models.IntegerField(
                        help_text="Año académico en el que se dicta la comisión"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Identificador interno de la comisión", max_length=32
                    ),
                ),
                ("cupo_maximo", models.IntegerField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABI", "Abierta"),
                            ("CER", "Cerrada"),
                            ("SUS", "Suspendida"),
                        ],
                        default="ABI",
                        max_length=3,
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "docente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comisiones",
                        to="core.docente",
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comisiones",
                        to="core.horariocatedra",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comisiones",
                        to="core.materia",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comisiones",
                        to="core.turno",
                    ),
                ),
            ],
            options={
                "ordering": ["anio_lectivo", "materia__nombre", "codigo"],
            },
        ),
        migrations.AddField(
            model_name="inscripcionmateriaalumno",
            name="comision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscripciones",
                to="core.comision",
            ),
        ),
        migrations.AddField(
            model_name="inscripcionmateriaalumno",
            name="comision_solicitada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscripciones_solicitadas",
                to="core.comision",
            ),
        ),
        migrations.AddIndex(
            model_name="inscripcionmateriaalumno",
            index=models.Index(
                fields=["estudiante", "anio"], name="core_inscri_estudia_5e9556_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inscripcionmateriaalumno",
            index=models.Index(
                fields=["estudiante", "estado"], name="core_inscri_estudia_ff670e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="comision",
            unique_together={("materia", "anio_lectivo", "codigo")},
        ),
    ]
