# Generated by Django 5.2.6 on 2025-10-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_inscripcionmateriaalumno_estado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="regularidad",
            name="asistencia_porcentaje",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="regularidad",
            name="excepcion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="regularidad",
            name="inscripcion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regularidades_historial",
                to="core.inscripcionmateriaalumno",
            ),
        ),
        migrations.AddField(
            model_name="regularidad",
            name="nota_trabajos_practicos",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="regularidad",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
    ]
