# Generated by Django 5.2.6 on 2025-10-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_regularidad_asistencia_porcentaje_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventanahabilitacion",
            name="periodo",
            field=models.CharField(
                blank=True,
                help_text="Solo para inscripciones a materias: '1C_ANUALES' o '2C'.",
                max_length=16,
                null=True,
            ),
        ),
    ]
