# Generated by Django 5.2.6 on 2025-10-22 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_staffasignacion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffasignacion",
            options={
                "verbose_name": "Asignación de staff",
                "verbose_name_plural": "Asignaciones de staff",
            },
        ),
    ]
