# Generated by Django 5.2.6 on 2025-10-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_messagetopic_conversation_conversationaudit_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffasignacion",
            name="rol",
            field=models.CharField(
                choices=[
                    ("bedel", "Bedel"),
                    ("coordinador", "Coordinador"),
                    ("tutor", "Tutor"),
                ],
                max_length=20,
            ),
        ),
    ]
