# Generated by Django 5.2.6 on 2025-11-03 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_acta_examen"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="planillaregularidad",
            new_name="core_planil_profeso_3a564c_idx",
            old_name="core_planil_profeso_e43bd0_idx",
        ),
        migrations.RenameIndex(
            model_name="planillaregularidad",
            new_name="core_planil_materia_90e19b_idx",
            old_name="core_planil_materia_9c2ae7_idx",
        ),
        migrations.AlterField(
            model_name="planillaregularidad",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="planillaregularidaddocente",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="planillaregularidadfila",
            name="asistencia_porcentaje",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="planillaregularidadfila",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="planillaregularidadhistorial",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="regularidadformato",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="regularidadplantilla",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
