# Generated by Django 5.2.6 on 2025-11-06 10:15

import django.db.models.deletion
from django.db import migrations, models


def seed_requisitos(apps, schema_editor):
    Template = apps.get_model("core", "RequisitoDocumentacionTemplate")
    Profesorado = apps.get_model("core", "Profesorado")
    ProfesoradoReq = apps.get_model("core", "ProfesoradoRequisitoDocumentacion")

    seeds = [
        {
            "codigo": "dni_legalizado",
            "titulo": "Fotocopia legalizada del DNI",
            "categoria": "GEN",
            "orden": 10,
        },
        {
            "codigo": "fotos_4x4",
            "titulo": "Dos fotos carnet 4x4",
            "categoria": "GEN",
            "orden": 20,
        },
        {
            "codigo": "folios_oficio",
            "titulo": "Tres folios oficio",
            "categoria": "GEN",
            "orden": 30,
        },
        {
            "codigo": "certificado_salud",
            "titulo": "Certificado de Buena Salud",
            "categoria": "GEN",
            "orden": 40,
        },
        {
            "codigo": "curso_introductorio_aprobado",
            "titulo": "Curso introductorio aprobado",
            "categoria": "GEN",
            "orden": 50,
        },
        {
            "codigo": "titulo_secundario_legalizado",
            "titulo": "Título secundario legalizado",
            "categoria": "SEC",
            "orden": 10,
        },
        {
            "codigo": "certificado_titulo_en_tramite",
            "titulo": "Certificado de título en trámite",
            "categoria": "SEC",
            "orden": 20,
            "obligatorio": False,
        },
        {
            "codigo": "analitico_legalizado",
            "titulo": "Analítico legalizado",
            "categoria": "SEC",
            "orden": 30,
        },
        {
            "codigo": "certificado_alumno_regular_sec",
            "titulo": "Certificado de alumno regular (secundario)",
            "categoria": "COM",
            "orden": 10,
            "obligatorio": False,
        },
        {
            "codigo": "adeuda_materias",
            "titulo": "Declaración de materias adeudadas",
            "descripcion": "Detalle de materias adeudadas y establecimiento.",
            "categoria": "COM",
            "orden": 20,
            "obligatorio": False,
        },
        {
            "codigo": "libreta_entregada",
            "titulo": "Libreta entregada",
            "categoria": "OTRO",
            "orden": 10,
            "obligatorio": False,
        },
    ]

    templates = {}
    for idx, seed in enumerate(seeds, start=1):
        defaults = {
            "titulo": seed["titulo"],
            "descripcion": seed.get("descripcion", ""),
            "categoria": seed.get("categoria", "GEN"),
            "obligatorio": seed.get("obligatorio", True),
            "orden": seed.get("orden", idx * 10),
            "activo": seed.get("activo", True),
        }
        template, _ = Template.objects.update_or_create(codigo=seed["codigo"], defaults=defaults)
        templates[template.codigo] = template

    profesorados = list(Profesorado.objects.all())
    if not profesorados:
        return

    for profesorado in profesorados:
        for template in templates.values():
            ProfesoradoReq.objects.get_or_create(
                profesorado=profesorado,
                codigo=template.codigo,
                defaults={
                    "template": template,
                    "titulo": template.titulo,
                    "descripcion": template.descripcion,
                    "categoria": template.categoria,
                    "obligatorio": template.obligatorio,
                    "orden": template.orden,
                    "activo": template.activo,
                    "personalizado": False,
                },
            )


def remove_requisitos(apps, schema_editor):
    Template = apps.get_model("core", "RequisitoDocumentacionTemplate")
    ProfesoradoReq = apps.get_model("core", "ProfesoradoRequisitoDocumentacion")
    ProfesoradoReq.objects.all().delete()
    Template.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_ventanahabilitacion_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequisitoDocumentacionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=64, unique=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("GEN", "Requisitos generales"),
                            ("SEC", "Secundario"),
                            ("COM", "Complementario"),
                            ("FOTO", "Foto"),
                            ("OTRO", "Otros"),
                        ],
                        default="GEN",
                        max_length=5,
                    ),
                ),
                ("obligatorio", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Requisito documental (plantilla)",
                "verbose_name_plural": "Requisitos documentales (plantillas)",
                "ordering": ["categoria", "orden", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="ProfesoradoRequisitoDocumentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=64)),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("GEN", "Requisitos generales"),
                            ("SEC", "Secundario"),
                            ("COM", "Complementario"),
                            ("FOTO", "Foto"),
                            ("OTRO", "Otros"),
                        ],
                        default="GEN",
                        max_length=5,
                    ),
                ),
                ("obligatorio", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "personalizado",
                    models.BooleanField(
                        default=False,
                        help_text="Se marca en True cuando el requisito fue editado específicamente para este profesorado.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profesorado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitos_documentacion",
                        to="core.profesorado",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instancias",
                        to="core.requisitodocumentaciontemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisito documental por profesorado",
                "verbose_name_plural": "Requisitos documentales por profesorado",
                "ordering": ["categoria", "orden", "codigo"],
                "unique_together": {("profesorado", "codigo")},
            },
        ),
        migrations.RunPython(seed_requisitos, remove_requisitos),
    ]
