# Generated by Django 5.2.6 on 2025-11-06 20:50

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_estudiante_carreras(apps, schema_editor):
    connection = schema_editor.connection
    introspection = connection.introspection
    old_table = "core_estudiante_carreras"
    if old_table not in introspection.table_names():
        return
    EstudianteCarrera = apps.get_model("core", "EstudianteCarrera")
    quoted_old = connection.ops.quote_name(old_table)
    cursor = connection.cursor()
    cursor.execute(f"SELECT estudiante_id, profesorado_id FROM {quoted_old}")
    rows = cursor.fetchall()
    objs = [
        EstudianteCarrera(estudiante_id=est_id, profesorado_id=prof_id)
        for est_id, prof_id in rows
    ]
    if objs:
        EstudianteCarrera.objects.bulk_create(objs, ignore_conflicts=True)
    cursor.execute(f"DROP TABLE {quoted_old}")


def seed_correlatividad_versions(apps, schema_editor):
    Version = apps.get_model("core", "CorrelatividadVersion")
    VersionDetalle = apps.get_model("core", "CorrelatividadVersionDetalle")
    Correlatividad = apps.get_model("core", "Correlatividad")
    Materia = apps.get_model("core", "Materia")

    plans = (
        Materia.objects
        .values_list("plan_de_estudio_id", "plan_de_estudio__profesorado_id")
        .distinct()
    )
    for plan_id, profesorado_id in plans:
        if not plan_id or not profesorado_id:
            continue
        correlativas = Correlatividad.objects.filter(
            materia_origen__plan_de_estudio_id=plan_id
        )
        if not correlativas.exists():
            continue
        version = Version.objects.create(
            plan_de_estudio_id=plan_id,
            profesorado_id=profesorado_id,
            nombre="Planilla base",
            descripcion="Generada automáticamente durante la migración.",
            cohorte_desde=2000,
            cohorte_hasta=None,
        )
        VersionDetalle.objects.bulk_create(
            [
                VersionDetalle(version=version, correlatividad=corr)
                for corr in correlativas
            ],
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_requisitodocumentaciontemplate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrelatividadVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Etiqueta para identificar la planilla (ej. Default 2023+).",
                        max_length=255,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "cohorte_desde",
                    models.PositiveIntegerField(
                        help_text="Año de cohorte inicial (inclusive)."
                    ),
                ),
                (
                    "cohorte_hasta",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Año de cohorte final (inclusive). Dejar vacío para aplicar en adelante.",
                        null=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_de_estudio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correlatividad_versiones",
                        to="core.plandeestudio",
                    ),
                ),
                (
                    "profesorado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correlatividad_versiones",
                        to="core.profesorado",
                    ),
                ),
            ],
            options={
                "ordering": ["plan_de_estudio_id", "cohorte_desde"],
                "unique_together": {("plan_de_estudio", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="EstudianteCarrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio_ingreso",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Año de ingreso/cohorte del estudiante en este profesorado.",
                        null=True,
                    ),
                ),
                ("cohorte", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carreras_detalle",
                        to="core.estudiante",
                    ),
                ),
                (
                    "profesorado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudiantes_detalle",
                        to="core.profesorado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación estudiante-profesorado",
                "verbose_name_plural": "Asignaciones estudiante-profesorado",
                "unique_together": {("estudiante", "profesorado")},
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="estudiante",
                    name="carreras",
                    field=models.ManyToManyField(
                        related_name="estudiantes",
                        through="core.EstudianteCarrera",
                        to="core.profesorado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorrelatividadVersionDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "correlatividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones",
                        to="core.correlatividad",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="core.correlatividadversion",
                    ),
                ),
            ],
            options={
                "unique_together": {("version", "correlatividad")},
            },
        ),
        migrations.RunPython(
            copy_existing_estudiante_carreras,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            seed_correlatividad_versions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
