# Generated by Django 5.2.6 on 2025-11-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_correlatividadversion_estudiantecarrera_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="correlatividadversion",
            name="vigencia_desde",
            field=models.DateField(
                blank=True,
                help_text="Fecha en la que comienza a regir esta versión.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="correlatividadversion",
            name="vigencia_hasta",
            field=models.DateField(
                blank=True,
                help_text="Fecha en la que deja de aplicarse esta versión (opcional).",
                null=True,
            ),
        ),
    ]
