# Generated by Django 5.2.6 on 2025-11-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_alter_preinscripcion_cuil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventanahabilitacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("INSCRIPCION", "Inscripcion (general)"),
                    ("MESAS_FINALES", "Mesas de examen - Finales"),
                    ("MESAS_EXTRA", "Mesas de examen - Extraordinarias"),
                    ("MESAS_LIBRES", "Mesas de examen - Libres"),
                    ("MATERIAS", "Inscripciones a Materias"),
                    ("CARRERAS", "Inscripciones a Carreras"),
                    ("COMISION", "Cambios de Comision"),
                    ("ANALITICOS", "Pedidos de Analiticos"),
                    ("EQUIVALENCIAS", "Pedidos de Equivalencias"),
                    ("PREINSCRIPCION", "Preinscripcion"),
                    ("CALENDARIO_CUATRIMESTRE", "Calendario academico - Cuatrimestres"),
                ],
                max_length=32,
            ),
        ),
    ]
