# Generated by Django 5.2.6 on 2025-11-11 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_alter_ventanahabilitacion_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoEquivalencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ANEXO_A", "Anexo A"), ("ANEXO_B", "Anexo B")],
                        max_length=16,
                    ),
                ),
                (
                    "ciclo_lectivo",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("profesorado_destino_nombre", models.CharField(max_length=255)),
                (
                    "plan_destino_resolucion",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "profesorado_origen_nombre",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "plan_origen_resolucion",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "establecimiento_origen",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "establecimiento_localidad",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "establecimiento_provincia",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("draft", "Borrador"), ("final", "Finalizado")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("bloqueado_en", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bloqueado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_equivalencia",
                        to="core.estudiante",
                    ),
                ),
                (
                    "plan_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_equivalencia_destino",
                        to="core.plandeestudio",
                    ),
                ),
                (
                    "profesorado_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_equivalencia_destino",
                        to="core.profesorado",
                    ),
                ),
                (
                    "ventana",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_equivalencia",
                        to="core.ventanahabilitacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PedidoEquivalenciaMateria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("formato", models.CharField(blank=True, default="", max_length=128)),
                (
                    "anio_cursada",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias",
                        to="core.pedidoequivalencia",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
    ]
