# Generated by Django 5.2.6 on 2025-11-12 09:19

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def forward_fill_mesa_codigo(apps, schema_editor):
    MesaExamen = apps.get_model("core", "MesaExamen")
    for mesa in MesaExamen.objects.all().order_by("id"):
        if mesa.codigo:
            continue
        fecha_ref = mesa.fecha or timezone.now().date()
        codigo = f"MESA-{fecha_ref.strftime('%Y%m%d')}-{mesa.id:05d}"
        MesaExamen.objects.filter(pk=mesa.pk).update(codigo=codigo)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_pedidoequivalencia_pedidoequivalenciamateria"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesaexamen",
            name="codigo",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="mesaexamen",
            name="docente_presidente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mesas_como_presidente",
                to="core.docente",
            ),
        ),
        migrations.AddField(
            model_name="mesaexamen",
            name="docente_vocal1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mesas_como_vocal1",
                to="core.docente",
            ),
        ),
        migrations.AddField(
            model_name="mesaexamen",
            name="docente_vocal2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mesas_como_vocal2",
                to="core.docente",
            ),
        ),
        migrations.AlterField(
            model_name="mesaexamen",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("FIN", "Ordinaria"),
                    ("EXT", "Extraordinaria"),
                    ("ESP", "Especial"),
                ],
                max_length=3,
            ),
        ),
        migrations.RunPython(forward_fill_mesa_codigo, migrations.RunPython.noop),
    ]
