# Generated by Django 5.2.6 on 2025-11-12 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def seed_historic_curso_intro_registros(apps, schema_editor):
    Estudiante = apps.get_model("core", "Estudiante")
    Registro = apps.get_model("core", "CursoIntroductorioRegistro")
    for est in Estudiante.objects.filter(datos_extra__curso_introductorio_aprobado=True).iterator():
        Registro.objects.get_or_create(
            estudiante=est,
            cohorte=None,
            defaults={
                "resultado": "APR",
                "es_historico": True,
                "resultado_at": timezone.now(),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_mesaexamen_codigo_mesaexamen_docente_presidente_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffasignacion",
            name="rol",
            field=models.CharField(
                choices=[
                    ("bedel", "Bedel"),
                    ("coordinador", "Coordinador"),
                    ("tutor", "Tutor"),
                    ("curso_intro", "Curso Introductorio"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ventanahabilitacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("INSCRIPCION", "Inscripcion (general)"),
                    ("MESAS_FINALES", "Mesas de examen - Finales"),
                    ("MESAS_EXTRA", "Mesas de examen - Extraordinarias"),
                    ("MESAS_LIBRES", "Mesas de examen - Libres"),
                    ("MATERIAS", "Inscripciones a Materias"),
                    ("CARRERAS", "Inscripciones a Carreras"),
                    ("COMISION", "Cambios de Comision"),
                    ("ANALITICOS", "Pedidos de Analiticos"),
                    ("EQUIVALENCIAS", "Pedidos de Equivalencias"),
                    ("PREINSCRIPCION", "Preinscripcion"),
                    ("CURSO_INTRODUCTORIO", "Curso Introductorio"),
                    ("CALENDARIO_CUATRIMESTRE", "Calendario academico - Cuatrimestres"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="CursoIntroductorioCohorte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=128)),
                ("anio_academico", models.IntegerField()),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("cupo", models.PositiveIntegerField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cohortes_curso_intro_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profesorado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curso_introductorio_cohortes",
                        to="core.profesorado",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curso_introductorio_cohortes",
                        to="core.turno",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cohortes_curso_intro_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ventana_inscripcion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curso_introductorio_cohortes",
                        to="core.ventanahabilitacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cohorte de Curso Introductorio",
                "verbose_name_plural": "Cohortes de Curso Introductorio",
                "ordering": ["-anio_academico", "-fecha_inicio", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CursoIntroductorioRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inscripto_en", models.DateTimeField(auto_now_add=True)),
                (
                    "asistencias_totales",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "nota_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente"),
                            ("APR", "Aprobado"),
                            ("DES", "Desaprobado"),
                            ("AUS", "Ausente"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("resultado_at", models.DateTimeField(blank=True, null=True)),
                ("es_historico", models.BooleanField(default=False)),
                (
                    "cohorte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros",
                        to="core.cursointroductoriocohorte",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curso_introductorio_registros",
                        to="core.estudiante",
                    ),
                ),
                (
                    "profesorado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curso_introductorio_registros",
                        to="core.profesorado",
                    ),
                ),
                (
                    "resultado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curso_introductorio_resultados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curso_introductorio_registros",
                        to="core.turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Curso Introductorio",
                "verbose_name_plural": "Registros Curso Introductorio",
                "ordering": ["-inscripto_en"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cohorte", "estudiante"),
                        name="unique_registro_cohorte_estudiante",
                    )
                ],
            },
        ),
        migrations.RunPython(
            code=seed_historic_curso_intro_registros,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
