# Generated by Django 5.2.6 on 2025-11-12 21:32

from django.db import migrations, models


def copy_ci_flag_from_datos_extra(apps, schema_editor):
    Estudiante = apps.get_model("core", "Estudiante")
    for est in Estudiante.objects.iterator():
        datos_extra = dict(est.datos_extra or {})
        if "curso_introductorio_aprobado" not in datos_extra:
            continue
        flag = bool(datos_extra.pop("curso_introductorio_aprobado"))
        update_fields = ["datos_extra"]
        if est.curso_introductorio_aprobado != flag:
            est.curso_introductorio_aprobado = flag
            update_fields.append("curso_introductorio_aprobado")
        est.datos_extra = datos_extra
        est.save(update_fields=update_fields)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_staffasignacion_rol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="curso_introductorio_aprobado",
            field=models.BooleanField(
                default=False,
                help_text="Indica si tiene aprobado el Curso Introductorio.",
            ),
        ),
        migrations.RunPython(copy_ci_flag_from_datos_extra, noop),
    ]
