# Generated by Django 5.2.6 on 2025-11-12 22:00

from django.db import migrations, models


def migrate_mesas_libres(apps, schema_editor):
    Ventana = apps.get_model("core", "VentanaHabilitacion")
    Ventana.objects.filter(tipo="MESAS_LIBRES").update(tipo="MESAS_EXTRA")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_estudiante_curso_introductorio_aprobado"),
    ]

    operations = [
        migrations.RunPython(migrate_mesas_libres, noop),
        migrations.AlterField(
            model_name="ventanahabilitacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("INSCRIPCION", "Inscripcion (general)"),
                    ("MESAS_FINALES", "Mesas de examen - Finales"),
                    ("MESAS_EXTRA", "Mesas de examen - Extraordinarias"),
                    ("MATERIAS", "Inscripciones a Materias"),
                    ("CARRERAS", "Inscripciones a Carreras"),
                    ("COMISION", "Cambios de Comision"),
                    ("ANALITICOS", "Pedidos de Analiticos"),
                    ("EQUIVALENCIAS", "Pedidos de Equivalencias"),
                    ("PREINSCRIPCION", "Preinscripcion"),
                    ("CURSO_INTRODUCTORIO", "Curso Introductorio"),
                    ("CALENDARIO_CUATRIMESTRE", "Calendario academico - Cuatrimestres"),
                ],
                max_length=32,
            ),
        ),
    ]
