# Generated by Django 5.2.6 on 2025-11-12 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_alter_ventanahabilitacion_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("nombre_usuario", models.CharField(blank=True, max_length=100)),
                ("roles", models.JSONField(blank=True, default=list)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "tipo_accion",
                    models.CharField(
                        choices=[
                            ("CRUD", "CRUD"),
                            ("AUTH", "Authentication"),
                            ("SYSTEM", "System"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("detalle_accion", models.CharField(blank=True, max_length=100)),
                ("entidad_afectada", models.CharField(blank=True, max_length=50)),
                ("id_entidad", models.CharField(blank=True, max_length=64)),
                (
                    "resultado",
                    models.CharField(
                        choices=[("OK", "Ok"), ("ERROR", "Error")],
                        default="OK",
                        max_length=8,
                    ),
                ),
                ("ip_origen", models.CharField(blank=True, max_length=45)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["usuario"], name="audit_log_usuario_5aa78d_idx"
                    ),
                    models.Index(fields=["accion"], name="audit_log_accion_92f925_idx"),
                    models.Index(
                        fields=["tipo_accion"], name="audit_log_tipo_ac_829fb0_idx"
                    ),
                    models.Index(
                        fields=["entidad_afectada", "id_entidad"],
                        name="audit_log_entidad_b966f1_idx",
                    ),
                ],
            },
        ),
    ]
