# Generated by Django 5.2.6 on 2025-11-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_auditlog_audit_log_request_a46c86_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidoequivalenciamateria",
            name="nota",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
