# Generated by Django 5.2.6 on 2025-11-13 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_pedido_equivalencia_materia_nota"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquivalenciaDisposicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("primera_carga", "Primera carga"),
                            ("secretaria", "Secretaría"),
                        ],
                        max_length=32,
                    ),
                ),
                ("numero_disposicion", models.CharField(max_length=64)),
                ("fecha_disposicion", models.DateField()),
                (
                    "observaciones",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equivalencia_disposiciones",
                        to="core.estudiante",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equivalencia_disposiciones",
                        to="core.plandeestudio",
                    ),
                ),
                (
                    "profesorado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equivalencia_disposiciones",
                        to="core.profesorado",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="EquivalenciaDisposicionDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.CharField(max_length=32)),
                (
                    "observaciones",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "disposicion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="core.equivalenciadisposicion",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equivalencia_disposiciones",
                        to="core.materia",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="equivalenciadisposicion",
            index=models.Index(
                fields=["estudiante", "profesorado", "numero_disposicion"],
                name="core_equiva_estudia_0f9316_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="equivalenciadisposiciondetalle",
            unique_together={("disposicion", "materia")},
        ),
    ]
