# Generated by Django 5.2.8 on 2025-12-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_regularidad_planilla_lock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mesaactaoral",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
