# Generated by Django 5.2.8 on 2025-12-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_mesaactaoral_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del docente (opcional)', null=True),
        ),
    ]
