# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp_password',
            field=models.CharField(
                max_length=128,
                blank=True,
                null=True,
                help_text='Contraseña temporal para envío por email (se borra después del primer login)'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credentials_sent_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='Fecha y hora en que se enviaron las credenciales por email'
            ),
        ),
    ]
