# Generated by Django 5.2.8 on 2026-02-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_inscripcionmateriaalumno_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inscripcionmateriaestudiante',
            new_name='core_inscri_estudia_2b46a2_idx',
            old_name='core_inscri_estudia_5e9556_idx',
        ),
        migrations.RenameIndex(
            model_name='inscripcionmateriaestudiante',
            new_name='core_inscri_estudia_31c690_idx',
            old_name='core_inscri_estudia_ff670e_idx',
        ),
        migrations.AddField(
            model_name='inscripcionmesa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='temp_password',
            field=models.CharField(blank=True, help_text='Contraseña temporal para envío por email (se borra después del primer login o envío)', max_length=128, null=True),
        ),
    ]
