# Generated by Django 5.2.8 on 2026-02-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_sync_missing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REGULARIDAD_MISMATCH', 'Discrepancia Regularidad'), ('IMPORT_ERROR', 'Error de Importación'), ('SYSTEM_ERROR', 'Error del Sistema'), ('SECURITY_ALERT', 'Alerta de Seguridad')], default='SYSTEM_ERROR', max_length=50)),
                ('mensaje', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resuelto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
