# Generated by Django 5.2.8 on 2026-02-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_systemlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='tipo',
            field=models.CharField(choices=[('REGULARIDAD_MISMATCH', 'Discrepancia Regularidad'), ('ACTA_MISMATCH', 'Discrepancia Acta Examen'), ('EQUIVALENCIA_MISMATCH', 'Discrepancia Equivalencia'), ('IMPORT_ERROR', 'Error de Importación'), ('SYSTEM_ERROR', 'Error del Sistema'), ('SECURITY_ALERT', 'Alerta de Seguridad')], default='SYSTEM_ERROR', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='planillaregularidadfila',
            constraint=models.UniqueConstraint(fields=('planilla', 'dni'), name='uniq_planilla_regularidad_fila_dni'),
        ),
    ]
