# Generated by Django 5.2.8 on 2026-03-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_unique_planilla_fila_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcionchecklist',
            name='articulo_7',
            field=models.BooleanField(default=False),
        ),
    ]
