# Generated by Django 5.2.8 on 2026-03-15 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_preinscripcionchecklist_articulo_7'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_index=True, max_length=20, unique=True)),
                ('cuil', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=50, null=True)),
                ('parentesco_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No binario / Otro')], max_length=1, null=True)),
                ('nacionalidad', models.CharField(blank=True, default='Argentina', max_length=100)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('localidad', models.CharField(blank=True, max_length=150, null=True)),
                ('provincia', models.CharField(blank=True, default='Tierra del Fuego', max_length=150)),
                ('pais', models.CharField(blank=True, default='Argentina', max_length=100)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOL', 'Soltero/a'), ('CAS', 'Casado/a'), ('DIV', 'Divorciado/a'), ('VIU', 'Viudo/a'), ('CON', 'Conviviente'), ('OTR', 'Otro')], max_length=3, null=True)),
                ('localidad_nac', models.CharField(blank=True, max_length=150, null=True)),
                ('provincia_nac', models.CharField(blank=True, max_length=150, null=True)),
                ('pais_nac', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='docente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='cuil',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='telefono',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='analitico_legalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='anio_ingreso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='articulo_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='certificado_salud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='certificado_titulo_en_tramite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cohorte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='condicion_salud_detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='condicion_salud_informada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cud_informado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='dni_legalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='domicilio_trabajo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='empleador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='folios_oficio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fotos_4x4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='horario_trabajo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='libreta_entregada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sec_establecimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sec_fecha_egreso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sec_localidad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sec_pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sec_provincia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sec_titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='titulo_secundario_legalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='trabaja',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preinscripcionchecklist',
            name='folios_oficio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docente_perfil', to='core.persona'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_perfil', to='core.persona'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='core.persona'),
        ),
    ]
