# Generated by Django 5.2.8 on 2026-03-15

from django.db import migrations
from django.db.models import F

def create_personas_for_profiles(apps, schema_editor):
    Estudiante = apps.get_model('core', 'Estudiante')
    Docente = apps.get_model('core', 'Docente')
    Persona = apps.get_model('core', 'Persona')
    User = apps.get_model('auth', 'User')

    # Migrar Estudiantes
    for est in Estudiante.objects.all():
        if not est.persona_id:
            user = est.user
            # El DNI de los estudiantes en la BD vieja podía estar en el field dni (en caso de que estuviese) o username
            dni_from_est = getattr(est, 'legajo', None) or user.username # asumiendo legajo = dni si era viejo
            dni_val = dni_from_est if str(dni_from_est).isdigit() else user.username

            persona = Persona.objects.create(
                dni=dni_val,
                nombre=user.first_name or "Sin Nombre",
                apellido=user.last_name or "Sin Apellido",
                email=user.email,
            )
            est.persona = persona
            est.save(update_fields=['persona'])
            
    # Migrar Docentes
    for doc in Docente.objects.all():
         if not doc.persona_id:
            user_docente = doc.user if hasattr(doc, 'user') else None
            if user_docente:
                persona = Persona.objects.create(
                    dni=user_docente.username,
                    nombre=user_docente.first_name or "Docente",
                    apellido=user_docente.last_name or "Docente",
                    email=user_docente.email,
                )
                doc.persona = persona
                doc.save(update_fields=['persona'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_persona_refactor_identidad'),
    ]

    operations = [
        migrations.RunPython(create_personas_for_profiles, migrations.RunPython.noop),
    ]

