# Generated by Django 5.2.8 on 2026-03-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_migrate_personas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'ordering': ['anio_lectivo', 'materia__nombre', 'codigo', 'orden']},
        ),
        migrations.AlterUniqueTogether(
            name='comision',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comision',
            name='orden',
            field=models.PositiveIntegerField(default=1, help_text='Orden de jerarquía/suplencia'),
        ),
        migrations.AddField(
            model_name='comision',
            name='rol',
            field=models.CharField(choices=[('TIT', 'Titular'), ('INT', 'Interino'), ('SUP', 'Suplente')], default='TIT', max_length=3),
        ),
        migrations.AlterField(
            model_name='comision',
            name='estado',
            field=models.CharField(choices=[('ABI', 'Abierta'), ('CER', 'Cerrada'), ('SUS', 'Suspendida'), ('LIC', 'En Licencia')], default='ABI', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='comision',
            unique_together={('materia', 'anio_lectivo', 'codigo', 'docente', 'rol', 'orden')},
        ),
    ]
