# Generated by Django 5.2.8 on 2026-03-23 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_comision_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion',
            name='cuil',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{8}-\\d{1}$', message='El CUIL debe tener el formato XX-XXXXXXXX-X.')]),
        ),
    ]
