# Generated by Django 5.2.8 on 2026-03-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_preinscripcion_cuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantecarrera',
            name='estado_academico',
            field=models.CharField(choices=[('ACT', 'Activo'), ('BAJ', 'Baja / Abandono'), ('EGR', 'Egresado'), ('SUS', 'Suspendido')], default='ACT', help_text='Estado académico del estudiante en esta carrera.', max_length=3),
        ),
    ]
