# Generated by Django 5.2.8 on 2026-03-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_estudiantecarrera_estado_academico'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha en que este EDI dejó de estar vigente. Null = activo.', null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AddField(
            model_name='materia',
            name='is_edi',
            field=models.BooleanField(default=False, help_text='Indica si esta materia es un Espacio de Definición Institucional', verbose_name='Es EDI'),
        ),
        migrations.AlterField(
            model_name='estudiantecarrera',
            name='estado_academico',
            field=models.CharField(choices=[('ACT', 'Activo'), ('BAJ', 'Baja / Abandono'), ('EGR', 'Egresado'), ('SUS', 'Suspendido'), ('INA', 'Inactivo')], default='ACT', help_text='Estado académico del estudiante en esta carrera.', max_length=3),
        ),
    ]
