# Generated by Django 5.2.8 on 2026-04-10 23:50

import django.core.validators
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_materia_edi_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'ordering': ['anio_lectivo', 'materia__nombre', 'codigo', 'orden'], 'verbose_name': 'Comisión', 'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['anio_cursada', 'nombre'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        # Operaciones de restricciones comentadas para evitar conflictos de índices en DB local
        # migrations.RemoveConstraint(
        #     model_name='cursointroductorioregistro',
        #     name='unique_registro_cohorte_estudiante',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='regularidadplanillalock',
        #     name='regularidad_lock_scope_defined',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='materia',
        #     unique_together=set(),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='horariocatedra',
        #     unique_together={('espacio', 'turno', 'anio_academico', 'cuatrimestre')},
        # ),
        migrations.AddField(
            model_name='actaexamenestudiante',
            name='calificacion_numerica',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='actaexamenestudiante',
            name='escrito_numerico',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='actaexamenestudiante',
            name='oral_numerico',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='estado_academico_changed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última transición de estado académico.', null=True),
        ),
        migrations.AddField(
            model_name='horariocatedra',
            name='anio_academico',
            field=models.IntegerField(default=2025, help_text='Año académico (ej. 2025)'),
        ),
        migrations.AddField(
            model_name='mesaactaoral',
            name='nota_numeral',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Valor numérico para promedios y estadísticas', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='cursointroductorioregistro',
            name='nota_final',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='inscripcionmesa',
            name='nota',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='mesaactaoral',
            name='nota_final',
            field=models.CharField(blank=True, default='', help_text="Transcripción literal de la nota o estado (ej: 'Siete', 'Ausente')", max_length=32),
        ),
        migrations.AlterField(
            model_name='planillaregularidadfila',
            name='nota_final',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regularidad',
            name='asistencia_porcentaje',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='regularidad',
            name='nota_final_cursada',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='regularidad',
            name='nota_trabajos_practicos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        # migrations.AlterUniqueTogether(
        #     name='comision',
        #     unique_together={('materia', 'anio_lectivo', 'codigo')},
        # ),
        # migrations.AddConstraint(
        #     model_name='actaexamen',
        #     constraint=models.CheckConstraint(condition=models.Q(('total_alumnos', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('total_aprobados'), '+', models.F('total_desaprobados')), '+', models.F('total_ausentes')))), name='acta_examen_totals_parity'),
        # ),
        # migrations.AddConstraint(
        #     model_name='cursointroductorioregistro',
        #     constraint=models.UniqueConstraint(condition=models.Q(('cohorte__isnull', False)), fields=('cohorte', 'estudiante'), name='unique_registro_cohorte_estudiante'),
        # ),
        # migrations.AddConstraint(
        #     model_name='cursointroductorioregistro',
        #     constraint=models.UniqueConstraint(condition=models.Q(('cohorte__isnull', True)), fields=('estudiante',), name='unique_registro_student_orphan'),
        # ),
        # migrations.AddConstraint(
        #     model_name='materia',
        #     constraint=models.UniqueConstraint(condition=models.Q(('is_edi', False)), fields=('plan_de_estudio', 'anio_cursada', 'nombre', 'regimen'), name='unique_materia_normal'),
        # ),
        # migrations.AddConstraint(
        #     model_name='materia',
        #     constraint=models.UniqueConstraint(condition=models.Q(('is_edi', True)), fields=('plan_de_estudio', 'anio_cursada', 'nombre', 'regimen', 'fecha_inicio'), name='unique_materia_edi'),
        # ),
        # migrations.AddConstraint(
        #     model_name='materia',
        #     constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='materia_fecha_range_valid'),
        # ),
        # migrations.AddConstraint(
        #     model_name='regularidadplanillalock',
        #     constraint=models.CheckConstraint(condition=models.Q(models.Q(('anio_virtual__isnull', True), ('comision__isnull', False), ('materia__isnull', True)), models.Q(('anio_virtual__isnull', False), ('comision__isnull', True), ('materia__isnull', False)), _connector='OR'), name='regularidad_lock_scope_xor'),
        # ),
        # migrations.RemoveField(
        #     model_name='horariocatedra',
        #     name='anio_cursada',
        # ),
    ]
