# Generated by Django 5.2.8 on 2026-04-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_cursointroductorioregistro_unique_registro_cohorte_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionmateriaestudiante',
            name='horario_laboral_metadata',
            field=models.JSONField(blank=True, help_text='En caso de motivo laboral, guarda el horario declarado por el alumno.', null=True),
        ),
        migrations.AddField(
            model_name='inscripcionmateriaestudiante',
            name='motivo_cambio',
            field=models.CharField(blank=True, choices=[('OVERLAP', 'Superposición de materias'), ('WORK', 'Motivos laborales')], help_text='Motivo por el cual se solicita el cambio de comisión.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcionmateriaestudiante',
            name='estado',
            field=models.CharField(choices=[('CONF', 'Confirmada'), ('PEND', 'Pendiente'), ('RECH', 'Rechazada'), ('ANUL', 'Anulada'), ('BAJA', 'Baja Voluntaria'), ('COND', 'Condicional')], default='CONF', max_length=4),
        ),
        migrations.AlterField(
            model_name='inscripcionmateriamovimiento',
            name='tipo',
            field=models.CharField(choices=[('INS', 'Inscripción'), ('CAN', 'Cancelación'), ('BAJ', 'Baja Voluntaria'), ('CAM', 'Solicitud de Cambio'), ('OTR', 'Otro cambio')], max_length=3),
        ),
    ]
