# Generated by Django 5.2.8 on 2026-04-12 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_inscripcionmateriaestudiante_horario_laboral_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionmateriaestudiante',
            name='cambio_comision_estado',
            field=models.CharField(blank=True, choices=[('PEND', 'Pendiente'), ('APRO', 'Aprobado'), ('RECH', 'Rechazado')], default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionmateriaestudiante',
            name='disposicion_numero',
            field=models.CharField(blank=True, help_text='Número de disposición que autoriza el cambio (cargado por tutor).', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pedidoanalitico',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('CONF', 'Confeccionado'), ('ENTR', 'Entregado')], default='PEND', max_length=4),
        ),
        migrations.AddField(
            model_name='pedidoanalitico',
            name='preparado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoanalitico',
            name='preparado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidoanalitico',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
