# Generated by Django 5.2.8 on 2026-04-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_comision_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantecarrera',
            name='estado_legajo',
            field=models.CharField(choices=[('COM', 'Completo'), ('INC', 'Incompleto / Condicional'), ('PEN', 'Pendiente de Revisión')], default='PEN', help_text='Estado del legajo físico del estudiante para esta carrera específica.', max_length=3),
        ),
    ]
