# Generated by Django 5.2.8 on 2026-04-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_migrate_estado_legajo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='materias_autorizadas',
            field=models.ManyToManyField(blank=True, help_text='Materias específicas autorizadas excepcionalmente para rendir.', related_name='estudiantes_autorizados', to='core.materia'),
        ),
    ]
