# Generated by Django 5.2.8 on 2026-04-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_remove_estudiantecarrera_estado_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularidad',
            name='en_resguardo',
            field=models.BooleanField(default=False, help_text='La nota está en resguardo hasta que el estudiante complete su legajo.'),
        ),
    ]
