# Generated by Django 5.2.8 on 2026-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_regularidad_en_resguardo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventanahabilitacion',
            name='tipo',
            field=models.CharField(choices=[('INSCRIPCION', 'Inscripcion (general)'), ('MESAS_FINALES', 'Mesas de examen - Finales'), ('MESAS_EXTRA', 'Mesas de examen - Extraordinarias'), ('MATERIAS', 'Inscripciones a Materias'), ('CARRERAS', 'Inscripciones a Carreras'), ('COMISION', 'Cambios de Comision'), ('ANALITICOS', 'Pedidos de Analiticos'), ('EQUIVALENCIAS', 'Pedidos de Equivalencias'), ('PREINSCRIPCION', 'Preinscripcion'), ('CURSO_INTRODUCTORIO', 'Curso Introductorio'), ('CALENDARIO_CUATRIMESTRE', 'Calendario academico - Cuatrimestres'), ('PLANILLA_REGULARIDAD', 'Entrega de planillas de regularidad')], max_length=32),
        ),
    ]
