# Generated by Django 5.2.8 on 2026-04-15 19:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_ventanahabilitacion_planilla_regularidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaCursada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número auto-generado (ej: PRP-2025-001).', max_length=32, unique=True)),
                ('anio_lectivo', models.PositiveSmallIntegerField()),
                ('cuatrimestre', models.CharField(choices=[('1C', '1° Cuatrimestre'), ('2C', '2° Cuatrimestre'), ('ANUAL', 'Anual')], max_length=8)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CERRADA', 'Cerrada'), ('REABIERTA', 'Reabierta')], default='BORRADOR', max_length=16)),
                ('fecha_entrega', models.DateField(blank=True, help_text='Fecha de cierre definitivo. Null mientras está en borrador.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planillas_cursada', to='core.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planillas_cursada', to='core.materia')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planillas_cursada', to='core.regularidadplantilla')),
                ('profesorado', models.ForeignKey(help_text='Profesorado donde se dicta la materia.', on_delete=django.db.models.deletion.PROTECT, related_name='planillas_cursada', to='core.profesorado')),
                ('profesorado_destino', models.ForeignKey(help_text="Profesorado al que pertenecen los estudiantes de esta planilla. Igual a 'profesorado' salvo en planillas inter-profesorado.", on_delete=django.db.models.deletion.PROTECT, related_name='planillas_cursada_destino', to='core.profesorado')),
            ],
            options={
                'ordering': ['-anio_lectivo', 'cuatrimestre', 'materia'],
            },
        ),
        migrations.CreateModel(
            name='PlanillaCursadaFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Posición alfabética en la planilla.')),
                ('asistencia_porcentaje', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('excepcion', models.BooleanField(default=False)),
                ('columnas_datos', models.JSONField(blank=True, default=dict, help_text='Notas de TP, parciales y demás columnas según la plantilla.')),
                ('situacion', models.CharField(blank=True, help_text='Calculada al cerrar la planilla.', max_length=32)),
                ('en_resguardo', models.BooleanField(default=False, help_text='True si la nota quedó en resguardo por legajo incompleto.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_cursada', to='core.estudiante')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='core.planillacursada')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='planillacursada',
            index=models.Index(fields=['docente', 'anio_lectivo', 'cuatrimestre'], name='core_planil_docente_b705ce_idx'),
        ),
        migrations.AddIndex(
            model_name='planillacursada',
            index=models.Index(fields=['profesorado_destino', 'anio_lectivo'], name='core_planil_profeso_13ab25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planillacursadafila',
            unique_together={('planilla', 'orden')},
        ),
    ]
