# Generated by Django 5.2.8 on 2026-04-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_planilla_cursada'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionmateriaestudiante',
            name='materia_origen',
            field=models.ForeignKey(blank=True, help_text='Materia equivalente en el profesorado de origen del estudiante. Solo se llena en cambios de comisión inter-profesorado. Al cerrar la planilla de regularidad, la nota se genera sobre esta materia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_inter_profesorado', to='core.materia'),
        ),
    ]
