# Generated by Django 5.2.8 on 2026-04-15 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_inscripcion_materia_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillacursadafila',
            name='inscripcion',
            field=models.ForeignKey(blank=True, help_text='Inscripción original. Permite resolver materia_origen al cerrar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_cursada_filas', to='core.inscripcionmateriaestudiante'),
        ),
    ]
