# Generated by Django 5.2.8 on 2026-05-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_planillacursadafila_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='adeuda_materias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='adeuda_materias_detalle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='certificado_alumno_regular_sec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='es_certificacion_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='escuela_secundaria',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='incumbencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='titulo_terciario_univ',
            field=models.BooleanField(default=False),
        ),
    ]
