# Generated by Django 5.2.8 on 2026-05-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_estudiante_adeuda_materias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaexamen',
            name='codigo',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='mesaexamen',
            name='codigo',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
