# Generated by Django 5.2.8 on 2026-05-11 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_alter_actaexamen_codigo_alter_mesaexamen_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'Procesada'), ('REC', 'Rechazada')], default='PEN', max_length=3)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_mesa', to='core.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
                ('mesa_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mesaexamen')),
                ('ventana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ventanahabilitacion')),
            ],
            options={
                'verbose_name': 'Solicitud de mesa',
                'verbose_name_plural': 'Solicitudes de mesa',
                'unique_together': {('estudiante', 'materia', 'ventana')},
            },
        ),
    ]
