# Generated by Django 5.2.8 on 2026-05-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_solicitudmesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmesa',
            name='modalidad',
            field=models.CharField(choices=[('REG', 'Regular'), ('LIB', 'Libre')], default='REG', max_length=3),
        ),
    ]
