# Generated by Django 5.2.8 on 2026-05-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_alter_solicitudmesa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaexamen',
            name='numero_mesa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
