# Generated by Django 5.2.8 on 2026-05-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_add_numero_mesa_to_mesaexamen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='folios_oficio',
            field=models.BooleanField(default=False),
        ),
    ]
