# Generated by Django 5.2.8 on 2026-05-14 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_residenciacondicional'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='residenciacondicional',
            name='unique_residencia_condicional_por_ciclo',
        ),
        migrations.AlterUniqueTogether(
            name='residenciacondicional',
            unique_together={('estudiante', 'materia_residencia', 'ciclo_lectivo')},
        ),
    ]
