# Generated by Django 5.2.8 on 2026-05-14 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_estudiante_folios_oficio'),
        ('core', '0103_remove_residenciacondicional_unique_residencia_condicional_por_ciclo_and_more'),
    ]

    operations = [
    ]
