# Generated by Django 5.2.8 on 2026-05-14 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_merge_20260514_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaexamen',
            name='estudiante_exclusivo',
            field=models.ForeignKey(blank=True, help_text='Solo para mesas ESP: el estudiante para quien fue creada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_exclusivas', to='core.estudiante'),
        ),
    ]
