# Generated by Django 5.2.8 on 2026-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_mesaexamen_estudiante_exclusivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaexamen',
            name='activa',
            field=models.BooleanField(default=True, help_text='False cuando la mesa fue descartada administrativamente (soft-delete).'),
        ),
    ]
