# Generated by Django 5.2.8 on 2026-05-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_mesaexamen_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantecarrera',
            name='adeuda_materias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='adeuda_materias_detalle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='analitico_legalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='articulo_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='certificado_alumno_regular_sec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='certificado_salud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='certificado_titulo_en_tramite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='curso_introductorio_aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='dni_legalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='es_certificacion_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='escuela_secundaria',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='estado_legajo',
            field=models.CharField(choices=[('COM', 'Completo'), ('INC', 'Incompleto / Condicional'), ('PEN', 'Pendiente de Revisión')], default='PEN', help_text='Estado del legajo físico del estudiante para esta carrera.', max_length=3),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='folios_oficio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='fotos_4x4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='incumbencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='libreta_entregada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='titulo_secundario_legalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='titulo_terciario_univ',
            field=models.BooleanField(default=False),
        ),
    ]
