# Generated by Django 5.2.8 on 2026-06-14 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_migrate_legajo_data_to_estudiantecarrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='temp_password',
        ),
    ]
