# Generated by Django 5.2.8 on 2026-06-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_remove_userprofile_temp_password'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='estudiantecarrera',
            index=models.Index(fields=['estado_academico', 'profesorado'], name='core_estudi_estado__451335_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['apellido', 'nombre'], name='core_person_apellid_8a90b9_idx'),
        ),
    ]
