# Generated by Django 5.2.8 on 2026-06-22 22:15

from django.db import migrations
from django.db.models import Count


def migrate_and_fix_duplicate_checklists_and_codes(apps, schema_editor):
    Preinscripcion = apps.get_model('core', 'Preinscripcion')
    PreinscripcionChecklist = apps.get_model('core', 'PreinscripcionChecklist')
    EstudianteCarrera = apps.get_model('core', 'EstudianteCarrera')

    # 1. Reparación de códigos duplicados
    duplicates = (
        Preinscripcion.objects.values('codigo')
        .annotate(num_entries=Count('id'))
        .filter(num_entries__gt=1)
    )

    count_fixed = 0
    for dup in duplicates:
        code = dup['codigo']
        if not code:
            continue
        # Obtener todas las preinscripciones con ese código, ordenadas por ID
        entries = list(Preinscripcion.objects.filter(codigo=code).order_by('id'))
        # Conservamos el primero con su código original, y regeneramos el código de los duplicados
        for idx, p in enumerate(entries):
            if idx > 0:
                p.codigo = f'PRE-{p.anio}-{p.id:04d}'
                p.save(update_fields=['codigo'])
                count_fixed += 1

    # 2. Resetear checklists activos no confirmados a False para alumnos con al menos una preinscripción confirmada
    fields = [
        'dni_legalizado', 'fotos_4x4', 'certificado_salud', 'folios_oficio',
        'titulo_secundario_legalizado', 'certificado_titulo_en_tramite',
        'analitico_legalizado', 'articulo_7', 'adeuda_materias',
        'adeuda_materias_detalle', 'escuela_secundaria', 'certificado_alumno_regular_sec',
        'es_certificacion_docente', 'titulo_terciario_univ', 'incumbencia',
        'curso_introductorio_aprobado', 'libreta_entregada'
    ]

    est_con_confirmada = Preinscripcion.objects.filter(estado='Confirmada').values_list('alumno_id', flat=True).distinct()

    count_cl = 0
    count_ec = 0

    for est_id in est_con_confirmada:
        # Buscar preinscripciones no confirmadas del mismo alumno
        pre_no_conf = Preinscripcion.objects.filter(alumno_id=est_id, activa=True).exclude(estado='Confirmada')
        for pre in pre_no_conf:
            cl = getattr(pre, 'checklist', None)
            if cl:
                tiene_checks = any([
                    getattr(cl, 'dni_legalizado', False),
                    getattr(cl, 'fotos_4x4', False),
                    getattr(cl, 'certificado_salud', False),
                    getattr(cl, 'folios_oficio', False),
                    getattr(cl, 'titulo_secundario_legalizado', False),
                    getattr(cl, 'certificado_titulo_en_tramite', False),
                    getattr(cl, 'analitico_legalizado', False),
                ])
                if tiene_checks:
                    # Resetear checklist
                    for f in fields:
                        if hasattr(cl, f):
                            val = getattr(cl, f)
                            if isinstance(val, bool):
                                setattr(cl, f, False)
                            elif isinstance(val, int):
                                setattr(cl, f, 0)
                            else:
                                setattr(cl, f, '')
                    cl.save()
                    count_cl += 1

            # También limpiar la correspondiente EstudianteCarrera
            ec = EstudianteCarrera.objects.filter(estudiante_id=est_id, profesorado=pre.carrera).first()
            if ec:
                for f in fields:
                    if hasattr(ec, f):
                        val = getattr(ec, f)
                        if isinstance(val, bool):
                            setattr(ec, f, False)
                        elif isinstance(val, int):
                            setattr(ec, f, 0)
                        else:
                            setattr(ec, f, '')
                ec.estado_legajo = 'PEN'  # Pendiente de Revisión
                ec.save()
                count_ec += 1

    print(f'Reparación en migración completada. Códigos corregidos: {count_fixed}, Checklists reseteados: {count_cl}, Carreras reseteadas: {count_ec}')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_add_foto_to_persona'),
    ]

    operations = [
        migrations.RunPython(migrate_and_fix_duplicate_checklists_and_codes),
    ]
