# Generated by Django 5.2.8 on 2026-06-29 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_migrate_and_fix_duplicate_checklists_and_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillaregularidad',
            name='comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_regularidad', to='core.comision'),
        ),
    ]
