# Generated by Django 5.2.8 on 2026-06-30 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_planillaregularidad_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaexamen',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_cargadas', to='core.mesaexamen'),
        ),
    ]
