# Generated by Django 5.2.8

from django.db import migrations

def backfill_acta_mesa(apps, schema_editor):
    ActaExamen = apps.get_model('core', 'ActaExamen')
    MesaExamen = apps.get_model('core', 'MesaExamen')
    
    for acta in ActaExamen.objects.filter(mesa__isnull=True):
        modalidad = 'LIB' if acta.tipo == 'LIB' else 'REG'
        mesa = MesaExamen.objects.filter(
            materia_id=acta.materia_id,
            fecha=acta.fecha,
            modalidad=modalidad
        ).first()
        if mesa:
            acta.mesa = mesa
            acta.save(update_fields=['mesa'])

def reverse_backfill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_actaexamen_mesa'),
    ]

    operations = [
        migrations.RunPython(backfill_acta_mesa, reverse_backfill),
    ]
