# Generated by Django 5.2.8 on 2026-08-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_backfill_acta_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlatividad',
            name='tipo',
            field=models.CharField(choices=[('RPC', 'Regular para Cursar'), ('APC', 'Aprobada para Cursar'), ('SPC', 'Simultánea para Cursar'), ('APR', 'Aprobada para Rendir Final')], max_length=3),
        ),
    ]
