# Generated by Django 5.2.8 on 2026-08-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_alter_correlatividad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='suplente',
            field=models.ForeignKey(blank=True, help_text='Docente suplente asignado cuando el estado es LICENCIA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplencias', to='core.docente'),
        ),
    ]
