# Generated by Django 5.2.8 on 2026-08-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_comision_suplente'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='estado_suplente',
            field=models.CharField(choices=[('ABI', 'Abierta'), ('CER', 'Cerrada'), ('SUS', 'Suspendida'), ('LIC', 'En Licencia')], default='ABI', help_text='Estado del Suplente 1', max_length=3),
        ),
        migrations.AddField(
            model_name='comision',
            name='estado_suplente_2',
            field=models.CharField(choices=[('ABI', 'Abierta'), ('CER', 'Cerrada'), ('SUS', 'Suspendida'), ('LIC', 'En Licencia')], default='ABI', help_text='Estado del Suplente 2', max_length=3),
        ),
        migrations.AddField(
            model_name='comision',
            name='estado_suplente_3',
            field=models.CharField(choices=[('ABI', 'Abierta'), ('CER', 'Cerrada'), ('SUS', 'Suspendida'), ('LIC', 'En Licencia')], default='ABI', help_text='Estado del Suplente 3', max_length=3),
        ),
        migrations.AddField(
            model_name='comision',
            name='estado_suplente_4',
            field=models.CharField(choices=[('ABI', 'Abierta'), ('CER', 'Cerrada'), ('SUS', 'Suspendida'), ('LIC', 'En Licencia')], default='ABI', help_text='Estado del Suplente 4', max_length=3),
        ),
        migrations.AddField(
            model_name='comision',
            name='suplente_2',
            field=models.ForeignKey(blank=True, help_text='Suplente 2 asignado cuando el Suplente 1 está en LICENCIA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplencias_2', to='core.docente'),
        ),
        migrations.AddField(
            model_name='comision',
            name='suplente_3',
            field=models.ForeignKey(blank=True, help_text='Suplente 3 asignado cuando el Suplente 2 está en LICENCIA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplencias_3', to='core.docente'),
        ),
        migrations.AddField(
            model_name='comision',
            name='suplente_4',
            field=models.ForeignKey(blank=True, help_text='Suplente 4 asignado cuando el Suplente 3 está en LICENCIA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplencias_4', to='core.docente'),
        ),
    ]
