# Generated by Django 5.2.8 on 2026-08-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_comision_estado_suplente_comision_estado_suplente_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaactaoral',
            name='estado_conformidad',
            field=models.CharField(choices=[('PEN', 'Pendiente de notificación'), ('CON', 'Notificado y sin objeción'), ('DIS', 'Notificado y en disconformidad'), ('TIM', 'Notificado y sin objeción (por tiempo cumplido)')], db_index=True, default='PEN', help_text='Estado de la notificación y conformidad del estudiante', max_length=3),
        ),
        migrations.AddField(
            model_name='mesaactaoral',
            name='notificado_en',
            field=models.DateTimeField(blank=True, help_text='Momento en que el docente guardó la nota del acta oral y se inició la ventana de 10 min', null=True),
        ),
        migrations.AddField(
            model_name='mesaactaoral',
            name='observaciones_estudiante',
            field=models.TextField(blank=True, default='', help_text='Observación opcional del estudiante al manifestar disconformidad'),
        ),
        migrations.AddField(
            model_name='mesaactaoral',
            name='respondido_en',
            field=models.DateTimeField(blank=True, help_text='Momento en que el estudiante respondió o se cerró automáticamente por timeout', null=True),
        ),
    ]
