# Generated by Django 5.2.8 on 2026-08-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_mesaactaoral_estado_conformidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventanahabilitacion',
            name='tipo',
            field=models.CharField(choices=[('INSCRIPCION', 'Inscripcion (general)'), ('MESAS_FINALES', 'Mesas de examen - Finales'), ('MESAS_EXTRA', 'Mesas de examen - Extraordinarias'), ('MATERIAS', 'Inscripciones a Materias'), ('CARRERAS', 'Inscripciones a Carreras'), ('COMISION', 'Cambios de Comision'), ('ANALITICOS', 'Pedidos de Analiticos'), ('EQUIVALENCIAS', 'Pedidos de Equivalencias'), ('PREINSCRIPCION', 'Preinscripcion'), ('CURSO_INTRODUCTORIO', 'Curso Introductorio'), ('CALENDARIO_CUATRIMESTRE', 'Calendario academico - Cuatrimestres'), ('PLANILLA_REGULARIDAD', 'Entrega de planillas de regularidad'), ('MATERIAS_GESTION', 'Inscripciones a Materias (Gestión / Bedelía)'), ('COMISION_GESTION', 'Cambios de Comisión (Gestión / Bedelía)')], max_length=32),
        ),
    ]
