# Generated by Django 5.2.8 on 2026-09-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_alter_ventanahabilitacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventanahabilitacion',
            name='permite_libres',
            field=models.BooleanField(default=False, help_text='Indica si en este período se permite la solicitud o examen en condición libre (especialmente para extraordinarias).'),
        ),
    ]
