# Generated by Django 5.2.8 on 2026-09-02 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_ventanahabilitacion_permite_libres'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiesgoAcademicoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_riesgo', models.CharField(choices=[('rojo', 'Riesgo Crítico'), ('amarillo', 'Riesgo Medio'), ('verde', 'Trayectoria Regular')], db_index=True, max_length=10)),
                ('motivos', models.JSONField(default=list, help_text='Lista de razones concretas que dispararon el nivel de riesgo.')),
                ('fecha_calculo', models.DateField(db_index=True, help_text='Fecha del snapshot del cálculo (permite evolución temporal).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos_academicos', to='core.estudiante')),
                ('profesorado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_riesgo', to='core.profesorado')),
            ],
            options={
                'verbose_name': 'Riesgo Académico de Estudiante',
                'verbose_name_plural': 'Riesgos Académicos de Estudiantes',
                'ordering': ['-fecha_calculo', 'nivel_riesgo'],
                'indexes': [models.Index(fields=['fecha_calculo', 'nivel_riesgo'], name='core_riesgo_fecha_c_640409_idx'), models.Index(fields=['profesorado', 'nivel_riesgo'], name='core_riesgo_profeso_6f16ec_idx')],
                'unique_together': {('estudiante', 'fecha_calculo')},
            },
        ),
    ]
