# Generated by Django 5.2.17 on 2026-09-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_riesgoacademicoestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaexamen',
            name='clave_registral',
            field=models.CharField(blank=True, editable=False, help_text="Identificación única 'libro/folio' de las actas numeradas digitalmente. Queda en NULL para las actas históricas en papel, que tienen folios repetidos y no pueden cumplir la unicidad.", max_length=160, null=True, unique=True),
        ),
    ]
