# Generated by Django 5.2.17 on 2026-09-07 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_actaexamen_clave_registral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mesaexamen',
            constraint=models.UniqueConstraint(fields=('materia', 'fecha', 'modalidad'), name='mesa_unica_por_materia_fecha_modalidad'),
        ),
    ]
