# Generated by Django 5.2.17 on 2026-09-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_mesaexamen_mesa_unica_por_materia_fecha_modalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Token Revocado',
                'verbose_name_plural': 'Tokens Revocados',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_invalid_before',
            field=models.DateTimeField(blank=True, help_text='Tokens emitidos antes de esta fecha se consideran revocados.', null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='autorizado_rendir',
            field=models.BooleanField(default=False, help_text='Autorización excepcional para rendir exámenes finales con legajo incompleto. Solo puede ser activado por Secretaría.'),
        ),
    ]
