# Generated by Django 5.2.17 on 2026-09-22 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_revokedtoken_userprofile_token_invalid_before_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorradorActaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, default='', max_length=32)),
                ('libro', models.CharField(blank=True, default='', max_length=32)),
                ('observaciones_generales', models.TextField(blank=True, default='')),
                ('docente_presidente_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('docente_presidente_dni', models.CharField(blank=True, default='', max_length=16)),
                ('docente_vocal1_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('docente_vocal1_dni', models.CharField(blank=True, default='', max_length=16)),
                ('docente_vocal2_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('docente_vocal2_dni', models.CharField(blank=True, default='', max_length=16)),
                ('estudiantes_csv', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True, help_text='False cuando el acta final se generó/cerró y este borrador queda obsoleto.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borradores_acta_final', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrador_acta_final', to='core.mesaexamen')),
            ],
            options={
                'verbose_name': 'Borrador de acta final',
                'verbose_name_plural': 'Borradores de acta final',
            },
        ),
        migrations.CreateModel(
            name='BorradorActaOral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_numero', models.CharField(blank=True, default='', max_length=64)),
                ('folio_numero', models.CharField(blank=True, default='', max_length=64)),
                ('fecha', models.CharField(blank=True, default='', max_length=16)),
                ('curso', models.CharField(blank=True, default='', max_length=128)),
                ('nota_final', models.CharField(blank=True, default='', max_length=32)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('temas_alumno_csv', models.TextField(blank=True, default='')),
                ('temas_docente_csv', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True, help_text='False cuando el acta oral se generó y este borrador queda obsoleto.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borradores_acta_oral', to=settings.AUTH_USER_MODEL)),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrador_acta_oral', to='core.inscripcionmesa')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borradores_acta_oral', to='core.mesaexamen')),
            ],
            options={
                'verbose_name': 'Borrador de acta oral',
                'verbose_name_plural': 'Borradores de acta oral',
            },
        ),
    ]
